import { Constructor } from './types';

// Authentic Historical Constructors (Teams currently not on the 2026 grid)
// Complete with authentic liveries, eras, championships, and legendary members (drivers & leadership)
export const HISTORICAL_CONSTRUCTORS: Constructor[] = [
  {
    id: 101,
    name: 'Brawn',
    full_name: 'Brawn GP Formula One Team',
    color_hex: '#B8FD38', // Iconic High-Vis Fluorescent Yellow / Lime
    country_code: 'GBR',
    era: '2009',
    is_active: false,
    base_location: 'Brackley, United Kingdom',
    championships: { wdc: 1, wcc: 1 },
    notable_drivers: ['Jenson Button', 'Rubens Barrichello'],
    description: 'The greatest fairytale in motorsport history. Formed from the ashes of Honda, Brawn GP pioneered the double diffuser and achieved a 100% World Championship sweep in their solitary season of competition.',
    members: [
      { name: 'Jenson Button', role: 'Driver #22 (2009 World Champion)', nationality: 'GBR', notes: '6 Grand Prix Victories, 95 Championship Points' },
      { name: 'Rubens Barrichello', role: 'Driver #23 (P3 World Championship)', nationality: 'BRA', notes: '2 Grand Prix Victories (Valencia, Monza)' },
      { name: 'Ross Brawn', role: 'Team Principal & Founder', nationality: 'GBR', notes: 'Mastermind behind the BGP 001 and double diffuser' },
      { name: 'Jörg Zander', role: 'Technical Director', nationality: 'GER', notes: 'Chief aerodynamic & chassis architect' },
    ],
  },
  {
    id: 102,
    name: 'Renault',
    full_name: 'Renault F1 Team',
    color_hex: '#FFF500', // Iconic Mild Seven Yellow & Sky Blue
    country_code: 'FRA',
    era: '2002–2011, 2016–2020',
    is_active: false,
    base_location: 'Enstone, United Kingdom / Viry-Châtillon, France',
    championships: { wdc: 2, wcc: 2 },
    notable_drivers: ['Fernando Alonso', 'Giancarlo Fisichella', 'Jarno Trulli', 'Robert Kubica', 'Daniel Ricciardo'],
    description: 'Dominant powerhouse of the mid-2000s V10 and V8 eras. Led by Fernando Alonso, Renault ended Ferrari and Michael Schumacher’s reign with consecutive World Championships in 2005 and 2006.',
    members: [
      { name: 'Fernando Alonso', role: 'Lead Driver (2005 & 2006 World Champion)', nationality: 'ESP', notes: 'Consecutive World Titles, 14 Victories with Renault' },
      { name: 'Giancarlo Fisichella', role: 'Driver (2005–2007)', nationality: 'ITA', notes: '2 Grand Prix Wins (Australia 2005, Malaysia 2006)' },
      { name: 'Jarno Trulli', role: 'Driver (2002–2004)', nationality: 'ITA', notes: 'Monaco GP 2004 Winner from Pole Position' },
      { name: 'Robert Kubica', role: 'Driver (2010)', nationality: 'POL', notes: '3 Podiums, legendary Monaco qualifying performance' },
      { name: 'Daniel Ricciardo', role: 'Driver (2019–2020)', nationality: 'AUS', notes: '2 Podiums (Eifel, Imola 2020)' },
      { name: 'Flavio Briatore', role: 'Managing Director', nationality: 'ITA', notes: 'Architect of the 2005-2006 championship campaigns' },
      { name: 'Pat Symonds', role: 'Executive Director of Engineering', nationality: 'GBR', notes: 'Technical mastermind of tuned mass damper' },
    ],
  },
  {
    id: 103,
    name: 'Toyota',
    full_name: 'Panasonic Toyota Racing',
    color_hex: '#EE0000', // Toyota Racing Red & White
    country_code: 'JPN',
    era: '2002–2009',
    is_active: false,
    base_location: 'Cologne, Germany',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jarno Trulli', 'Ralf Schumacher', 'Timo Glock', 'Olivier Panis', 'Kamui Kobayashi'],
    description: 'Japanese manufacturing giant with a state-of-the-art facility in Cologne. Achieved 13 podium finishes and 3 pole positions in 139 Grands Prix.',
    members: [
      { name: 'Jarno Trulli', role: 'Driver #8 / #9 (2005–2009)', nationality: 'ITA', notes: '7 Podiums, 2 Pole Positions (USA 2005, Bahrain 2009)' },
      { name: 'Ralf Schumacher', role: 'Driver #17 (2005–2007)', nationality: 'GER', notes: '3 Podiums, Pole Position Japan 2005' },
      { name: 'Timo Glock', role: 'Driver #10 / #12 (2008–2009)', nationality: 'GER', notes: '3 Podiums, P2 Singapore 2009 & Hungary 2008' },
      { name: 'Kamui Kobayashi', role: 'Driver (2009)', nationality: 'JPN', notes: 'Sensational late-season debut at Interlagos and Abu Dhabi' },
      { name: 'Ove Andersson', role: 'Team Principal (2002–2003)', nationality: 'SWE', notes: 'Founding leader of Toyota Motorsport GmbH' },
      { name: 'John Howett', role: 'Team President (2004–2009)', nationality: 'GBR', notes: 'Led team to best-ever P4 in 2005 Constructors Championship' },
    ],
  },
  {
    id: 104,
    name: 'BMW Sauber',
    full_name: 'BMW Sauber F1 Team',
    color_hex: '#1C4E9C', // BMW Motorsport Blue & White
    country_code: 'GER',
    era: '2006–2009',
    is_active: false,
    base_location: 'Hinwil, Switzerland & Munich, Germany',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Robert Kubica', 'Nick Heidfeld', 'Sebastian Vettel', 'Jacques Villeneuve'],
    description: 'Dynamic partnership between BMW and Peter Sauber. Secured P2 in the 2007 World Constructors Championship and a famous 1-2 victory at the 2008 Canadian Grand Prix.',
    members: [
      { name: 'Robert Kubica', role: 'Lead Driver (2006–2009)', nationality: 'POL', notes: 'Canada 2008 Grand Prix Winner, 1 Pole, 9 Podiums' },
      { name: 'Nick Heidfeld', role: 'Driver (2006–2009)', nationality: 'GER', notes: '8 Podiums with BMW Sauber, exceptional consistency' },
      { name: 'Sebastian Vettel', role: 'Test & Reserve Driver (2006–2007)', nationality: 'GER', notes: 'Scored point on F1 debut (USA 2007) as youngest driver in history' },
      { name: 'Jacques Villeneuve', role: 'Driver (2006)', nationality: 'CAN', notes: '1997 World Champion in inaugural BMW Sauber season' },
      { name: 'Mario Theissen', role: 'BMW Motorsport Director', nationality: 'GER', notes: 'Head of BMW Formula 1 programme' },
      { name: 'Peter Sauber', role: 'Founder & Consultant', nationality: 'SUI', notes: 'Hinwil racing icon' },
    ],
  },
  {
    id: 105,
    name: 'Toro Rosso',
    full_name: 'Scuderia Toro Rosso',
    color_hex: '#469BFF', // Toro Rosso Metallic Electric Blue
    country_code: 'ITA',
    era: '2006–2019',
    is_active: false,
    base_location: 'Faenza, Italy',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Sebastian Vettel', 'Max Verstappen', 'Daniel Ricciardo', 'Carlos Sainz', 'Pierre Gasly'],
    description: 'The premier nursery of Formula 1 World Champions. Built from Minardi, Toro Rosso shocked the world when Sebastian Vettel won the rain-soaked 2008 Italian Grand Prix from pole position.',
    members: [
      { name: 'Sebastian Vettel', role: 'Driver (2007–2008)', nationality: 'GER', notes: 'Maiden F1 Victory at wet Monza 2008 from Pole' },
      { name: 'Max Verstappen', role: 'Driver (2015–2016)', nationality: 'NED', notes: 'Youngest driver to start a GP (17y 166d), P4 in Hungary & USA' },
      { name: 'Daniel Ricciardo', role: 'Driver (2012–2013)', nationality: 'AUS', notes: 'Graduated to Red Bull Racing after standout drives' },
      { name: 'Carlos Sainz', role: 'Driver (2015–2017)', nationality: 'ESP', notes: 'Impressed in rookie pairing with Verstappen' },
      { name: 'Pierre Gasly', role: 'Driver (2017–2019)', nationality: 'FRA', notes: 'Incredible P2 podium finish at Brazilian GP 2019' },
      { name: 'Franz Tost', role: 'Team Principal', nationality: 'AUT', notes: 'Legendary leader who nurtured over 15 F1 drivers' },
    ],
  },
  {
    id: 106,
    name: 'AlphaTauri',
    full_name: 'Scuderia AlphaTauri',
    color_hex: '#5E8FAA', // AlphaTauri Navy & White
    country_code: 'ITA',
    era: '2020–2023',
    is_active: false,
    base_location: 'Faenza, Italy',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Pierre Gasly', 'Yuki Tsunoda', 'Nyck de Vries', 'Liam Lawson', 'Daniel Ricciardo'],
    description: 'Premium Red Bull fashion rebrand of the Faenza squad. Pierre Gasly delivered a fairytale victory at the 2020 Italian Grand Prix in one of the most emotional podiums in modern F1.',
    members: [
      { name: 'Pierre Gasly', role: 'Driver #10 (2020–2022)', nationality: 'FRA', notes: 'Italian Grand Prix Winner (Monza 2020), P3 Azerbaijan 2021' },
      { name: 'Yuki Tsunoda', role: 'Driver #22 (2021–2023)', nationality: 'JPN', notes: 'Sensational rookie season with P4 in Abu Dhabi 2021' },
      { name: 'Liam Lawson', role: 'Reserve Driver (2023)', nationality: 'NZL', notes: 'Scored points at Singapore GP 2023 during 5-race stand-in' },
      { name: 'Franz Tost', role: 'Team Principal (2020–2023)', nationality: 'AUT', notes: 'Concluded illustrious 18-year career as team boss in 2023' },
    ],
  },
  {
    id: 107,
    name: 'Force India',
    full_name: 'Sahara Force India F1 Team',
    color_hex: '#F596C8', // BWT Pink & Saffron/Green/White
    country_code: 'IND',
    era: '2008–2018',
    is_active: false,
    base_location: 'Silverstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Sergio Pérez', 'Nico Hülkenberg', 'Giancarlo Fisichella', 'Adrian Sutil', 'Esteban Ocon'],
    description: 'The ultimate overachievers of Formula 1. Punched above their budget year after year to achieve back-to-back P4 finishes in the World Constructors Championship in 2016 and 2017.',
    members: [
      { name: 'Sergio Pérez', role: 'Driver #11 (2014–2018)', nationality: 'MEX', notes: '5 Podiums with Force India (Bahrain, Russia, Monaco, Baku)' },
      { name: 'Nico Hülkenberg', role: 'Driver #27 (2012, 2014–2016)', nationality: 'GER', notes: 'Led 2012 Brazilian GP, cornerstone of P4 WCC runs' },
      { name: 'Giancarlo Fisichella', role: 'Driver (2008–2009)', nationality: 'ITA', notes: 'Historic Pole Position and P2 at Spa-Francorchamps 2009' },
      { name: 'Adrian Sutil', role: 'Driver (2008–2011, 2013)', nationality: 'GER', notes: '109 Grand Prix starts, long-time stalwart' },
      { name: 'Vijay Mallya', role: 'Team Principal & Managing Director', nationality: 'IND', notes: 'Charismatic founder who brought Indian identity to F1' },
      { name: 'Otmar Szafnauer', role: 'Chief Operating Officer', nationality: 'USA', notes: 'Managed high-efficiency operations on lean budgets' },
    ],
  },
  {
    id: 108,
    name: 'Racing Point',
    full_name: 'BWT Racing Point F1 Team',
    color_hex: '#F596C8', // BWT Pink
    country_code: 'GBR',
    era: '2019–2020',
    is_active: false,
    base_location: 'Silverstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Sergio Pérez', 'Lance Stroll', 'Nico Hülkenberg'],
    description: 'Famous for the stunning RP20 "Pink Mercedes". Sergio Pérez drove from last place on lap 1 to take an extraordinary victory at the 2020 Sakhir Grand Prix.',
    members: [
      { name: 'Sergio Pérez', role: 'Driver #11 (2019–2020)', nationality: 'MEX', notes: 'Sakhir GP 2020 Winner, P4 in 2020 Drivers Championship' },
      { name: 'Lance Stroll', role: 'Driver #18 (2019–2020)', nationality: 'CAN', notes: 'Pole Position at wet Turkish GP 2020, 2 Podiums (Monza, Sakhir)' },
      { name: 'Nico Hülkenberg', role: 'Super Sub Driver #27 (2020)', nationality: 'GER', notes: 'Heroic P3 qualifying at 70th Anniversary GP Silverstone' },
      { name: 'Andrew Green', role: 'Technical Director', nationality: 'GBR', notes: 'Designed the race-winning RP20 package' },
    ],
  },
  {
    id: 109,
    name: 'Lotus F1',
    full_name: 'Lotus F1 Team',
    color_hex: '#E5C158', // Iconic JPS Black & Gold
    country_code: 'GBR',
    era: '2012–2015',
    is_active: false,
    base_location: 'Enstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Kimi Räikkönen', 'Romain Grosjean', 'Pastor Maldonado'],
    description: 'Enstone operation racing in timeless black and gold livery. Returned Kimi Räikkönen to F1 victory lane with legendary wins in Abu Dhabi 2012 ("Leave me alone, I know what I’m doing") and Australia 2013.',
    members: [
      { name: 'Kimi Räikkönen', role: 'Driver #7 / #9 (2012–2013)', nationality: 'FIN', notes: '2 Grand Prix Wins (Abu Dhabi 2012, Melbourne 2013), 15 Podiums' },
      { name: 'Romain Grosjean', role: 'Driver #8 / #11 (2012–2015)', nationality: 'FRA', notes: '10 Podiums with Lotus, blistering single-lap pace' },
      { name: 'Pastor Maldonado', role: 'Driver #13 (2014–2015)', nationality: 'VEN', notes: 'Piloted E22 and E23 hybrid challengers' },
      { name: 'Éric Boullier', role: 'Team Principal (2012–2014)', nationality: 'FRA', notes: 'Guided team to back-to-back P4 finishes in WCC' },
      { name: 'James Allison', role: 'Technical Director', nationality: 'GBR', notes: 'Pioneered ultra-compliant suspension and tyre wear advantage' },
    ],
  },
  {
    id: 110,
    name: 'Jaguar',
    full_name: 'Jaguar Racing F1 Team',
    color_hex: '#00594C', // Jaguar British Racing Green
    country_code: 'GBR',
    era: '2000–2004',
    is_active: false,
    base_location: 'Milton Keynes, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Eddie Irvine', 'Mark Webber', 'Johnny Herbert', 'Pedro de la Rosa', 'Christian Klien'],
    description: 'Ford Motor Company’s factory team in pristine British Racing Green with the leaping cat. Eddie Irvine claimed podiums in Monaco and Monza, paving the foundation for Red Bull Racing.',
    members: [
      { name: 'Eddie Irvine', role: 'Driver #7 / #8 (2000–2002)', nationality: 'GBR', notes: '2 Podiums (Monaco 2001, Monza 2002)' },
      { name: 'Mark Webber', role: 'Driver #14 (2003–2004)', nationality: 'AUS', notes: 'Qualifying heroics, regular front-row starts' },
      { name: 'Johnny Herbert', role: 'Driver #8 (2000)', nationality: 'GBR', notes: 'Final F1 season of 3x Grand Prix winner' },
      { name: 'Niki Lauda', role: 'Team Principal (2001–2002)', nationality: 'AUT', notes: '3x World Champion leading executive team' },
      { name: 'Bobby Rahal', role: 'Team Principal (2000–2001)', nationality: 'USA', notes: 'American motorsport legend' },
    ],
  },
  {
    id: 111,
    name: 'Jordan',
    full_name: 'Jordan Grand Prix',
    color_hex: '#FFE000', // Iconic Buzzin Hornets Yellow
    country_code: 'IRL',
    era: '1991–2005',
    is_active: false,
    base_location: 'Silverstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Heinz-Harald Frentzen', 'Giancarlo Fisichella', 'Jarno Trulli', 'Takuma Sato', 'Damon Hill'],
    description: 'Rock-and-roll team founded by Eddie Jordan with yellow liveries featuring hornet and shark mascots. Claimed 4 historic Grand Prix victories and finished P3 in the 1999 World Championship.',
    members: [
      { name: 'Heinz-Harald Frentzen', role: 'Driver #8 (1999–2001)', nationality: 'GER', notes: '2 Wins in 1999 (France, Italy), P3 in World Championship' },
      { name: 'Giancarlo Fisichella', role: 'Driver (1997, 2002–2003)', nationality: 'ITA', notes: 'Incredible wet-weather victory at Brazilian GP 2003' },
      { name: 'Jarno Trulli', role: 'Driver (2000–2001)', nationality: 'ITA', notes: 'Top qualifying specialist with Jordan' },
      { name: 'Takuma Sato', role: 'Driver (2002)', nationality: 'JPN', notes: 'Famous P5 points finish at home in Suzuka 2002' },
      { name: 'Eddie Jordan', role: 'Founder & Team Principal', nationality: 'IRL', notes: 'Legendary paddock personality and talent scout' },
    ],
  },
  {
    id: 112,
    name: 'BAR',
    full_name: 'British American Racing (BAR Honda)',
    color_hex: '#E6E6E6', // Lucky Strike White, Red Target & Silver
    country_code: 'GBR',
    era: '1999–2005',
    is_active: false,
    base_location: 'Brackley, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jenson Button', 'Jacques Villeneuve', 'Takuma Sato', 'Olivier Panis'],
    description: 'Backed by British American Tobacco and Honda power. Peaked in 2004 when Jenson Button scored 10 podiums to secure P2 in the Constructors Championship behind Ferrari.',
    members: [
      { name: 'Jenson Button', role: 'Driver #9 (2003–2005)', nationality: 'GBR', notes: '10 Podiums in 2004, P3 in World Drivers Championship' },
      { name: 'Jacques Villeneuve', role: 'Driver (1999–2003)', nationality: 'CAN', notes: '1997 World Champion, scored BAR’s first podiums in 2001' },
      { name: 'Takuma Sato', role: 'Driver (2003–2005)', nationality: 'JPN', notes: 'Podium finisher at 2004 United States Grand Prix' },
      { name: 'David Richards', role: 'Team Principal (2002–2004)', nationality: 'GBR', notes: 'Restructured team to achieve P2 WCC in 2004' },
      { name: 'Geoff Willis', role: 'Technical Director', nationality: 'GBR', notes: 'Designer of the potent 2004 BAR 006' },
    ],
  },
  {
    id: 113,
    name: 'Honda',
    full_name: 'Honda Racing F1 Team',
    color_hex: '#CC0000', // Championship White & Earth Dreams
    country_code: 'JPN',
    era: '2006–2008',
    is_active: false,
    base_location: 'Brackley, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jenson Button', 'Rubens Barrichello'],
    description: 'Full works Japanese manufacturer effort. Jenson Button drove an unforgettable wet race from 14th on the grid to score his maiden F1 victory at the 2006 Hungarian Grand Prix.',
    members: [
      { name: 'Jenson Button', role: 'Driver #12 / #7 / #16 (2006–2008)', nationality: 'GBR', notes: 'Maiden F1 Victory at Hungarian GP 2006 from 14th on the grid' },
      { name: 'Rubens Barrichello', role: 'Driver #11 / #8 / #17 (2006–2008)', nationality: 'BRA', notes: 'Superb wet P3 podium at British Grand Prix 2008' },
      { name: 'Nick Fry', role: 'Chief Executive Officer', nationality: 'GBR', notes: 'Oversaw Brackley factory management' },
      { name: 'Shuhei Nakamoto', role: 'Senior Technical Director', nationality: 'JPN', notes: 'Honda engineering leader' },
    ],
  },
  {
    id: 114,
    name: 'Minardi',
    full_name: 'Minardi F1 Team',
    color_hex: '#000000', // Minardi Black & Yellow
    country_code: 'ITA',
    era: '1985–2005',
    is_active: false,
    base_location: 'Faenza, Italy',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Fernando Alonso', 'Mark Webber', 'Jos Verstappen', 'Justin Wilson', 'Giancarlo Fisichella'],
    description: 'The most beloved independent team in the history of Formula 1. Operating on a fraction of rival budgets from Faenza, Minardi discovered and launched the careers of Fernando Alonso and Mark Webber.',
    members: [
      { name: 'Fernando Alonso', role: 'Driver (2001)', nationality: 'ESP', notes: 'Stunning rookie season outperforming far superior machinery' },
      { name: 'Mark Webber', role: 'Driver (2002)', nationality: 'AUS', notes: 'Heroic P5 on debut at Melbourne 2002 with historic 2 points' },
      { name: 'Justin Wilson', role: 'Driver (2003)', nationality: 'GBR', notes: 'Point scorer at Indianapolis 2003' },
      { name: 'Jos Verstappen', role: 'Driver (2003)', nationality: 'NED', notes: 'Rain master who topped Friday qualifying in France 2003' },
      { name: 'Gian Carlo Minardi', role: 'Founder', nationality: 'ITA', notes: 'Heart and soul of the Faenza racing institution' },
      { name: 'Paul Stoddart', role: 'Team Principal (2001–2005)', nationality: 'AUS', notes: 'Australian aviation entrepreneur who kept team fighting' },
    ],
  },
  {
    id: 115,
    name: 'Marussia',
    full_name: 'Marussia F1 Team / Manor Racing',
    color_hex: '#EE2020', // Manor Red, Black & Blue
    country_code: 'GBR',
    era: '2012–2016',
    is_active: false,
    base_location: 'Banbury, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jules Bianchi', 'Pascal Wehrlein', 'Esteban Ocon', 'Max Chilton', 'Alexander Rossi'],
    description: 'Brave independent British squad. Immortalized by Jules Bianchi’s magical P9 finish around the streets of Monaco in 2014, scoring the team’s first championship points.',
    members: [
      { name: 'Jules Bianchi', role: 'Driver #17 (2013–2014)', nationality: 'FRA', notes: 'Immortal P9 in Monaco 2014, beloved Ferrari academy hero' },
      { name: 'Pascal Wehrlein', role: 'Driver #94 (2016)', nationality: 'GER', notes: 'Scored famous championship point with P10 at Austrian GP 2016' },
      { name: 'Esteban Ocon', role: 'Driver #31 (2016)', nationality: 'FRA', notes: 'F1 debut season starting at Belgian Grand Prix 2016' },
      { name: 'Max Chilton', role: 'Driver #23 (2013–2014)', nationality: 'GBR', notes: 'Finished all 19 Grands Prix in rookie 2013 season' },
      { name: 'John Booth', role: 'Team Principal', nationality: 'GBR', notes: 'Rotherham racing veteran who guided Manor from junior tiers' },
    ],
  },
  {
    id: 116,
    name: 'Caterham',
    full_name: 'Caterham F1 Team',
    color_hex: '#00502F', // British Racing Green & Golden Yellow
    country_code: 'MAS',
    era: '2010–2014',
    is_active: false,
    base_location: 'Leafield, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Heikki Kovalainen', 'Jarno Trulli', 'Kamui Kobayashi', 'Marcus Ericsson', 'Vitaly Petrov'],
    description: 'Entered F1 in 2010 as Lotus Racing before becoming Caterham. Renowned for their iconic green and gold livery and fiercely passionate fanbase.',
    members: [
      { name: 'Heikki Kovalainen', role: 'Lead Driver (2010–2012)', nationality: 'FIN', notes: 'Q2 qualifying heroics in 2011 and 2012' },
      { name: 'Jarno Trulli', role: 'Driver (2010–2011)', nationality: 'ITA', notes: 'Veteran Grand Prix winner leading development' },
      { name: 'Vitaly Petrov', role: 'Driver (2012)', nationality: 'RUS', notes: 'P11 in dramatic wet Brazilian GP 2012 to claim P10 in WCC' },
      { name: 'Kamui Kobayashi', role: 'Driver (2014)', nationality: 'JPN', notes: 'Fan-funded return to Formula 1 in 2014' },
      { name: 'Tony Fernandes', role: 'Team Principal & Founder', nationality: 'MAS', notes: 'AirAsia entrepreneur who brought Malaysia back to F1' },
    ],
  },
  {
    id: 117,
    name: 'Super Aguri',
    full_name: 'Super Aguri F1 Team',
    color_hex: '#E60000', // White & Rising Sun Red
    country_code: 'JPN',
    era: '2006–2008',
    is_active: false,
    base_location: 'Leafield, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Takuma Sato', 'Anthony Davidson', 'Yuji Ide', 'Franck Montagny'],
    description: 'Founded in just 100 days by former F1 podium finisher Aguri Suzuki. Produced legendary moments including Takuma Sato passing World Champion Fernando Alonso for P6 in Canada 2007.',
    members: [
      { name: 'Takuma Sato', role: 'Driver #22 (2006–2008)', nationality: 'JPN', notes: 'Iconic P6 Canada 2007, P8 Spain 2007 (4 Championship Points)' },
      { name: 'Anthony Davidson', role: 'Driver #23 (2007–2008)', nationality: 'GBR', notes: 'Ran as high as P3 in Canada 2007' },
      { name: 'Aguri Suzuki', role: 'Team Founder & Principal', nationality: 'JPN', notes: 'First Japanese driver to score an F1 podium (Suzuka 1990)' },
      { name: 'Mark Preston', role: 'Technical Director', nationality: 'AUS', notes: 'Led engineering team from Arrows Leafield base' },
    ],
  },
  {
    id: 118,
    name: 'HRT',
    full_name: 'HRT Formula 1 Team (Hispania Racing)',
    color_hex: '#786048', // Titanium Gold, Matte Brown & White
    country_code: 'ESP',
    era: '2010–2012',
    is_active: false,
    base_location: 'Madrid, Spain',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Daniel Ricciardo', 'Pedro de la Rosa', 'Narain Karthikeyan', 'Vitantonio Liuzzi', 'Bruno Senna'],
    description: 'Spain’s first official Formula 1 constructor. Provided future 8-time Grand Prix winner Daniel Ricciardo with his Formula 1 debut in 2011.',
    members: [
      { name: 'Daniel Ricciardo', role: 'Driver #22 (2011)', nationality: 'AUS', notes: 'Red Bull Junior F1 debut season starting at Silverstone 2011' },
      { name: 'Pedro de la Rosa', role: 'Driver #22 (2012)', nationality: 'ESP', notes: 'Spanish veteran leading the squad in its final year' },
      { name: 'Narain Karthikeyan', role: 'Driver (2011–2012)', nationality: 'IND', notes: 'First Indian F1 driver, competed in inaugural Indian GP' },
      { name: 'Vitantonio Liuzzi', role: 'Driver (2011)', nationality: 'ITA', notes: 'Former F3000 champion' },
      { name: 'Luis Pérez-Sala', role: 'Team Principal (2011–2012)', nationality: 'ESP', notes: 'Former Minardi F1 driver' },
    ],
  },
  {
    id: 119,
    name: 'Arrows',
    full_name: 'Arrows Grand Prix International',
    color_hex: '#FF8000', // Orange Arrows & Black
    country_code: 'GBR',
    era: '1978–2002',
    is_active: false,
    base_location: 'Leafield, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jos Verstappen', 'Pedro de la Rosa', 'Heinz-Harald Frentzen'],
    description: 'Cult favorite with striking orange and black livery. Renowned for Jos Verstappen’s blistering wet-weather launches and overtaking displays in 2000-2001.',
    members: [
      { name: 'Jos Verstappen', role: 'Driver #18 (2000–2001)', nationality: 'NED', notes: 'Spectacular drives in wet conditions (Canada 2000 P5, Austria 2001 P6)' },
      { name: 'Pedro de la Rosa', role: 'Driver #19 (2000)', nationality: 'ESP', notes: 'Points finishes at Nürburgring and Hockenheim' },
      { name: 'Heinz-Harald Frentzen', role: 'Driver #20 (2002)', nationality: 'GER', notes: 'Points at Barcelona and Monaco with A23' },
      { name: 'Tom Walkinshaw', role: 'Team Owner & Boss', nationality: 'GBR', notes: 'Touring car legend and TWR motorsport founder' },
    ],
  },
  {
    id: 120,
    name: 'Prost',
    full_name: 'Prost Grand Prix',
    color_hex: '#002B7F', // French Bleu Gauloises
    country_code: 'FRA',
    era: '1997–2001',
    is_active: false,
    base_location: 'Guyancourt, France',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Jean Alesi', 'Nick Heidfeld', 'Heinz-Harald Frentzen', 'Jarno Trulli'],
    description: 'Founded by 4-time World Champion Alain Prost following the purchase of Ligier. Competed in patriotic French blue with passionate backing from Peugeot and Acer.',
    members: [
      { name: 'Jean Alesi', role: 'Driver #18 (2000–2001)', nationality: 'FRA', notes: 'Points finishes at Monaco, Canada, and Germany in 2001' },
      { name: 'Nick Heidfeld', role: 'Driver #19 (2000)', nationality: 'GER', notes: 'German rookie campaign alongside Alesi' },
      { name: 'Heinz-Harald Frentzen', role: 'Driver #18 (2001)', nationality: 'GER', notes: 'Sensational P4 qualifying at wet Spa 2001' },
      { name: 'Alain Prost', role: 'Founder & Team Principal', nationality: 'FRA', notes: '4x Formula 1 World Drivers Champion' },
    ],
  },
];

// Active 2026 Grid Constructors with Authentic Team Members & Leadership
export const ACTIVE_CONSTRUCTORS: Constructor[] = [
  {
    id: 1,
    name: 'McLaren',
    full_name: 'McLaren Formula 1 Team',
    color_hex: '#FF8000',
    country_code: 'GBR',
    era: '1966–Present (Active Grid)',
    is_active: true,
    base_location: 'Woking, United Kingdom',
    championships: { wdc: 12, wcc: 9 },
    notable_drivers: ['Lando Norris', 'Oscar Piastri', 'Ayrton Senna', 'Alain Prost', 'Lewis Hamilton', 'Mika Häkkinen'],
    description: 'Current 2024-2025 World Constructors Champions. Pioneered carbon-fibre monocoques with over 180 Grand Prix victories.',
    members: [
      { name: 'Lando Norris', role: 'Race Driver #4', nationality: 'GBR', notes: 'Lead Championship Contender' },
      { name: 'Oscar Piastri', role: 'Race Driver #81', nationality: 'AUS', notes: 'Grand Prix Winner & Sprint Champion' },
      { name: 'Andrea Stella', role: 'Team Principal', nationality: 'ITA', notes: 'Former Ferrari race engineer' },
      { name: 'Zak Brown', role: 'Chief Executive Officer', nationality: 'USA', notes: 'Architect of McLaren modern resurgence' },
    ],
  },
  {
    id: 2,
    name: 'Ferrari',
    full_name: 'Scuderia Ferrari HP',
    color_hex: '#E80020',
    country_code: 'ITA',
    era: '1950–Present (Active Grid)',
    is_active: true,
    base_location: 'Maranello, Italy',
    championships: { wdc: 15, wcc: 16 },
    notable_drivers: ['Charles Leclerc', 'Lewis Hamilton', 'Michael Schumacher', 'Niki Lauda', 'Kimi Räikkönen'],
    description: 'The most successful and storied team in Formula One history. The only team to have competed in every season since the championship began in 1950.',
    members: [
      { name: 'Charles Leclerc', role: 'Race Driver #16', nationality: 'MON', notes: 'Monaco GP Winner & Qualifying Master' },
      { name: 'Lewis Hamilton', role: 'Race Driver #44', nationality: 'GBR', notes: '7-time World Champion' },
      { name: 'Frédéric Vasseur', role: 'Team Principal', nationality: 'FRA', notes: 'Scuderia team boss' },
      { name: 'Loïc Serra', role: 'Chassis Technical Director', nationality: 'FRA', notes: 'Chassis & vehicle dynamics architect' },
    ],
  },
  {
    id: 3,
    name: 'Red Bull',
    full_name: 'Oracle Red Bull Racing',
    color_hex: '#3671C6',
    country_code: 'AUT',
    era: '2005–Present (Active Grid)',
    is_active: true,
    base_location: 'Milton Keynes, United Kingdom',
    championships: { wdc: 7, wcc: 6 },
    notable_drivers: ['Max Verstappen', 'Isack Hadjar', 'Sebastian Vettel', 'Daniel Ricciardo', 'Mark Webber'],
    description: '6-time World Constructors Champions who redefined ground-effect dominance under the technical leadership of Adrian Newey.',
    members: [
      { name: 'Max Verstappen', role: 'Race Driver #1', nationality: 'NED', notes: '4-time World Drivers Champion' },
      { name: 'Isack Hadjar', role: 'Race Driver #6', nationality: 'FRA', notes: 'Red Bull Racing Driver' },
      { name: 'Christian Horner', role: 'Team Principal & CEO', nationality: 'GBR', notes: 'Longest-serving team principal on the grid' },
      { name: 'Pierre Waché', role: 'Technical Director', nationality: 'FRA', notes: 'Chief of engineering design' },
    ],
  },
  {
    id: 4,
    name: 'Mercedes',
    full_name: 'Mercedes-AMG PETRONAS F1 Team',
    color_hex: '#27F4D2',
    country_code: 'GER',
    era: '1954–1955, 2010–Present (Active Grid)',
    is_active: true,
    base_location: 'Brackley, United Kingdom',
    championships: { wdc: 9, wcc: 8 },
    notable_drivers: ['George Russell', 'Andrea Kimi Antonelli', 'Lewis Hamilton', 'Nico Rosberg', 'Michael Schumacher'],
    description: 'Unprecedented 8 consecutive World Constructors Championships (2014–2021). The Silver Arrows represent engineering excellence.',
    members: [
      { name: 'George Russell', role: 'Race Driver #63', nationality: 'GBR', notes: 'Lead Driver & Grand Prix Winner' },
      { name: 'Andrea Kimi Antonelli', role: 'Race Driver #12', nationality: 'ITA', notes: 'Italian teenage prodigy' },
      { name: 'Toto Wolff', role: 'Team Principal & CEO', nationality: 'AUT', notes: 'Co-owner and 8x championship boss' },
      { name: 'James Allison', role: 'Technical Director', nationality: 'GBR', notes: 'Architect of multiple title-winning cars' },
    ],
  },
  {
    id: 5,
    name: 'Aston Martin',
    full_name: 'Aston Martin Aramco F1 Team',
    color_hex: '#229971',
    country_code: 'GBR',
    era: '2021–Present (Active Grid)',
    is_active: true,
    base_location: 'Silverstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Fernando Alonso', 'Lance Stroll', 'Sebastian Vettel'],
    description: 'Iconic British luxury brand with a cutting-edge £200M Technology Campus and wind tunnel at Silverstone.',
    members: [
      { name: 'Fernando Alonso', role: 'Race Driver #14', nationality: 'ESP', notes: '2-time World Champion' },
      { name: 'Lance Stroll', role: 'Race Driver #18', nationality: 'CAN', notes: 'Multi-podium finisher & pole sitter' },
      { name: 'Mike Krack', role: 'Team Principal', nationality: 'LUX', notes: 'Motorsport director' },
      { name: 'Dan Fallows', role: 'Technical Director', nationality: 'GBR', notes: 'Former Red Bull aerodynamics chief' },
    ],
  },
  {
    id: 6,
    name: 'Williams',
    full_name: 'Williams Racing',
    color_hex: '#64C4FF',
    country_code: 'GBR',
    era: '1977–Present (Active Grid)',
    is_active: true,
    base_location: 'Grove, United Kingdom',
    championships: { wdc: 7, wcc: 9 },
    notable_drivers: ['Alexander Albon', 'Carlos Sainz', 'Nigel Mansell', 'Alain Prost', 'Damon Hill', 'Jacques Villeneuve'],
    description: 'Independent heritage team with 9 World Constructors Championships, founded by Sir Frank Williams and Sir Patrick Head.',
    members: [
      { name: 'Alexander Albon', role: 'Race Driver #23', nationality: 'THA', notes: 'Lead Driver' },
      { name: 'Carlos Sainz', role: 'Race Driver #55', nationality: 'ESP', notes: 'Multi-Grand Prix Winner' },
      { name: 'James Vowles', role: 'Team Principal', nationality: 'GBR', notes: 'Former Mercedes Chief Strategist' },
      { name: 'Pat Fry', role: 'Chief Technical Officer', nationality: 'GBR', notes: 'Veteran engineering director' },
    ],
  },
  {
    id: 7,
    name: 'Alpine',
    full_name: 'BWT Alpine F1 Team',
    color_hex: '#0093CC',
    country_code: 'FRA',
    era: '2021–Present (Active Grid)',
    is_active: true,
    base_location: 'Enstone, United Kingdom',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Pierre Gasly', 'Jack Doohan', 'Esteban Ocon', 'Fernando Alonso'],
    description: 'Renault Group’s flagship performance brand. Delivered Hungary 2021 Grand Prix victory and double Brazil 2024 podium.',
    members: [
      { name: 'Pierre Gasly', role: 'Race Driver #10', nationality: 'FRA', notes: 'Grand Prix Winner' },
      { name: 'Franco Colapinto', role: 'Race Driver #43', nationality: 'ARG', notes: 'Alpine Formula 1 Driver' },
      { name: 'Oliver Oakes', role: 'Team Principal', nationality: 'GBR', notes: 'Youngest team boss on the grid' },
      { name: 'Flavio Briatore', role: 'Executive Advisor', nationality: 'ITA', notes: 'Renault executive advisor' },
    ],
  },
  {
    id: 8,
    name: 'Haas',
    full_name: 'MoneyGram Haas F1 Team',
    color_hex: '#B6BABD',
    country_code: 'USA',
    era: '2016–Present (Active Grid)',
    is_active: true,
    base_location: 'Kannapolis, USA & Banbury, UK',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Esteban Ocon', 'Oliver Bearman', 'Nico Hülkenberg', 'Kevin Magnussen', 'Romain Grosjean'],
    description: 'America’s Formula One team, founded by industrialist Gene Haas. Utilizes technical partnership with Scuderia Ferrari and Toyota Gazoo Racing.',
    members: [
      { name: 'Esteban Ocon', role: 'Race Driver #31', nationality: 'FRA', notes: 'Grand Prix Winner' },
      { name: 'Oliver Bearman', role: 'Race Driver #87', nationality: 'GBR', notes: 'Ferrari Academy young star' },
      { name: 'Ayao Komatsu', role: 'Team Principal', nationality: 'JPN', notes: 'Former chief race engineer' },
      { name: 'Andrea De Zordo', role: 'Technical Director', nationality: 'ITA', notes: 'Chief technical designer' },
    ],
  },
  {
    id: 9,
    name: 'RB',
    full_name: 'Visa Cash App RB F1 Team',
    color_hex: '#6692FF',
    country_code: 'ITA',
    era: '2024–Present (Active Grid)',
    is_active: true,
    base_location: 'Faenza, Italy',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Liam Lawson', 'Yuki Tsunoda', 'Daniel Ricciardo', 'Isack Hadjar'],
    description: 'Red Bull’s dynamic team based in Faenza and Milton Keynes, competing with Honda RBPT powertrains.',
    members: [
      { name: 'Liam Lawson', role: 'Race Driver #30', nationality: 'NZL', notes: 'Lead RB Formula 1 Driver' },
      { name: 'Yuki Tsunoda', role: 'Race Driver #22', nationality: 'JPN', notes: '5th Season in F1' },
      { name: 'Laurent Mekies', role: 'Team Principal', nationality: 'FRA', notes: 'Former FIA Safety Director and Ferrari Sporting Director' },
      { name: 'Jody Egginton', role: 'Technical Director', nationality: 'GBR', notes: 'Chief designer' },
    ],
  },
  {
    id: 10,
    name: 'Audi',
    full_name: 'Audi Revolut Formula 1 Team',
    color_hex: '#E30613',
    country_code: 'GER',
    era: '2026–Present (Active Grid)',
    is_active: true,
    base_location: 'Hinwil, Switzerland & Neuburg, Germany',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Nico Hülkenberg', 'Gabriel Bortoleto'],
    description: 'The official Audi factory works team in Formula One, running bespoke Audi power units and cutting-edge chassis developed at Hinwil and Neuburg.',
    members: [
      { name: 'Nico Hülkenberg', role: 'Race Driver #27', nationality: 'GER', notes: 'Over 220 Grand Prix starts' },
      { name: 'Gabriel Bortoleto', role: 'Race Driver #5', nationality: 'BRA', notes: 'F2 & F3 Champion rookie prodigy' },
      { name: 'Mattia Binotto', role: 'Chief Operating & Chief Technical Officer', nationality: 'ITA', notes: 'Leading Audi F1 transition' },
      { name: 'Jonathan Wheatley', role: 'Team Principal', nationality: 'GBR', notes: 'Former Red Bull Sporting Director' },
    ],
  },
  {
    id: 11,
    name: 'Cadillac',
    full_name: 'Cadillac Formula 1 Team',
    color_hex: '#C0C0C0',
    country_code: 'USA',
    era: '2026–Present (Active Grid)',
    is_active: true,
    base_location: 'Fishers, Indiana, USA & Silverstone, UK',
    championships: { wdc: 0, wcc: 0 },
    notable_drivers: ['Valtteri Bottas', 'Sergio Pérez'],
    description: 'General Motors and TWG Global factory works entry competing in the FIA Formula One World Championship as the 11th constructor.',
    members: [
      { name: 'Valtteri Bottas', role: 'Race Driver #77', nationality: 'FIN', notes: '10-time Grand Prix Winner' },
      { name: 'Sergio Pérez', role: 'Race Driver #11', nationality: 'MEX', notes: '6-time Grand Prix Winner' },
      { name: 'Graeme Lowdon', role: 'Team Principal', nationality: 'GBR', notes: 'Veteran Formula 1 executive' },
    ],
  },
];

export const ALL_CONSTRUCTORS: Constructor[] = [
  ...ACTIVE_CONSTRUCTORS,
  ...HISTORICAL_CONSTRUCTORS,
];
