import { RaceResult } from './types';

function getTeamColorHex(teamName: string = ''): string {
  const t = (teamName || '').toLowerCase().trim();
  if (t.includes('mclaren')) return '#FF8000';
  if (t.includes('ferrari')) return '#E80020';
  if (t.includes('mercedes')) return '#27F4D2';
  if (t.includes('red bull')) return '#3671C6';
  if (t.includes('aston martin')) return '#229971';
  if (t.includes('williams')) return '#64C4FF';
  if (t.includes('alpine')) return '#0093CC';
  if (t.includes('haas')) return '#B6BABD';
  if (t.includes('cadillac')) return '#C0C0C0';
  if (t.includes('audi')) return '#E30613';
  if (t.includes('kick') || (t.includes('sauber') && !t.includes('bmw'))) return '#52E252';
  if (t.includes('rb') || t.includes('racing bulls')) return '#6692FF';
  return '#FF1801';
}

export const OFFICIAL_2026_RESULTS: Record<number, RaceResult> = {
  4: {
    race_id: 4,
    season: 2026,
    round_number: 4,
    race_name: 'Bahrain Grand Prix',
    circuit_name: 'Bahrain International Circuit',
    country: 'Bahrain',
    country_code: 'BHR',
    date: '2026-04-12',
    status: 'CANCELLED',
    cancellation_reason: 'OFFICIAL FIA NOTICE: The Bahrain Grand Prix at Sakhir was cancelled and removed from the 2026 championship calendar.',
    laps_completed: 0,
    total_laps: 0,
    podium: null,
    top_finishers: [],
    fastest_lap: null,
    pole_position: null,
  },
  5: {
    race_id: 5,
    season: 2026,
    round_number: 5,
    race_name: 'Saudi Arabian Grand Prix',
    circuit_name: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    country_code: 'KSA',
    date: '2026-04-19',
    status: 'CANCELLED',
    cancellation_reason: 'OFFICIAL FIA NOTICE: The Saudi Arabian Grand Prix at Jeddah was cancelled and removed from the 2026 championship calendar.',
    laps_completed: 0,
    total_laps: 0,
    podium: null,
    top_finishers: [],
    fastest_lap: null,
    pole_position: null,
  },
  1: {
    race_id: 1,
    season: 2026,
    round_number: 1,
    race_name: "Australian Grand Prix",
    circuit_name: "Albert Park Grand Prix Circuit",
    country: "Australia",
    country_code: "AUS",
    date: "2026-03-08",
    status: 'COMPLETED',
    laps_completed: 58,
    total_laps: 58,
    podium: {
      p1: { position: 1, driver: { id: 101, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "1:23:06.801", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 201, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "+2.974", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 301, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, time_or_gap: "+15.519", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, lap_time: "1:22.091", lap_number: 43 },
    pole_position: { driver: { id: 998, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:23:06.801" },
      { position: 2, driver: { id: 401, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+2.974" },
      { position: 3, driver: { id: 402, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 15, time_or_gap: "+15.519" },
      { position: 4, driver: { id: 403, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+16.144" },
      { position: 5, driver: { id: 404, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 10, time_or_gap: "+51.741" },
      { position: 6, driver: { id: 405, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+54.617" },
      { position: 7, driver: { id: 406, driver_number: 87, broadcast_name: "O. BEARMAN", full_name: "Oliver Bearman", team_name: "Haas F1 Team", color_hex: getTeamColorHex("Haas F1 Team"), country_code: "BRI" }, team_name: "Haas F1 Team", team_color: getTeamColorHex("Haas F1 Team"), points: 6, time_or_gap: "+4.593" },
      { position: 8, driver: { id: 407, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 4, time_or_gap: "+11.816" },
      { position: 9, driver: { id: 408, driver_number: 5, broadcast_name: "G. BORTOLETO", full_name: "Gabriel Bortoleto", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "BRA" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 2, time_or_gap: "+12.775" },
      { position: 10, driver: { id: 409, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+29.027" },
    ],
  },
  2: {
    race_id: 2,
    season: 2026,
    round_number: 2,
    race_name: "Chinese Grand Prix",
    circuit_name: "Shanghai International Circuit",
    country: "China",
    country_code: "CHI",
    date: "2026-03-15",
    status: 'COMPLETED',
    laps_completed: 56,
    total_laps: 56,
    podium: {
      p1: { position: 1, driver: { id: 102, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:33:15.607", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 202, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "+5.515", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 302, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, time_or_gap: "+25.267", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:35.275", lap_number: 52 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:33:15.607" },
      { position: 2, driver: { id: 401, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+5.515" },
      { position: 3, driver: { id: 402, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 15, time_or_gap: "+25.267" },
      { position: 4, driver: { id: 403, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+28.894" },
      { position: 5, driver: { id: 404, driver_number: 87, broadcast_name: "O. BEARMAN", full_name: "Oliver Bearman", team_name: "Haas F1 Team", color_hex: getTeamColorHex("Haas F1 Team"), country_code: "BRI" }, team_name: "Haas F1 Team", team_color: getTeamColorHex("Haas F1 Team"), points: 10, time_or_gap: "+57.268" },
      { position: 6, driver: { id: 405, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 8, time_or_gap: "+59.647" },
      { position: 7, driver: { id: 406, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 6, time_or_gap: "+1:20.588" },
      { position: 8, driver: { id: 407, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 4, time_or_gap: "+1:27.247" },
      { position: 9, driver: { id: 408, driver_number: 55, broadcast_name: "C. SAINZ", full_name: "Carlos Sainz", team_name: "Williams", color_hex: getTeamColorHex("Williams"), country_code: "SPA" }, team_name: "Williams", team_color: getTeamColorHex("Williams"), points: 2, time_or_gap: "+11.673" },
      { position: 10, driver: { id: 409, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+12.403" },
    ],
  },
  3: {
    race_id: 3,
    season: 2026,
    round_number: 3,
    race_name: "Japanese Grand Prix",
    circuit_name: "Suzuka Circuit",
    country: "Japan",
    country_code: "JAP",
    date: "2026-03-29",
    status: 'COMPLETED',
    laps_completed: 53,
    total_laps: 53,
    podium: {
      p1: { position: 1, driver: { id: 103, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:28:03.403", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 203, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, time_or_gap: "+13.722", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 303, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, time_or_gap: "+15.270", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:32.432", lap_number: 49 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:28:03.403" },
      { position: 2, driver: { id: 401, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 18, time_or_gap: "+13.722" },
      { position: 3, driver: { id: 402, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 15, time_or_gap: "+15.270" },
      { position: 4, driver: { id: 403, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 12, time_or_gap: "+15.754" },
      { position: 5, driver: { id: 404, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 10, time_or_gap: "+23.479" },
      { position: 6, driver: { id: 405, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 8, time_or_gap: "+25.037" },
      { position: 7, driver: { id: 406, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+32.340" },
      { position: 8, driver: { id: 407, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 4, time_or_gap: "+32.677" },
      { position: 9, driver: { id: 408, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 2, time_or_gap: "+50.180" },
      { position: 10, driver: { id: 409, driver_number: 31, broadcast_name: "E. OCON", full_name: "Esteban Ocon", team_name: "Haas F1 Team", color_hex: getTeamColorHex("Haas F1 Team"), country_code: "FRE" }, team_name: "Haas F1 Team", team_color: getTeamColorHex("Haas F1 Team"), points: 1, time_or_gap: "+51.216" },
    ],
  },
  6: {
    race_id: 6,
    season: 2026,
    round_number: 6,
    race_name: "Miami Grand Prix",
    circuit_name: "Miami International Autodrome",
    country: "USA",
    country_code: "USA",
    date: "2026-05-03",
    status: 'COMPLETED',
    laps_completed: 57,
    total_laps: 57,
    podium: {
      p1: { position: 1, driver: { id: 106, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:33:19.273", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 206, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, time_or_gap: "+3.264", points: 18, fastest_lap: true },
      p3: { position: 3, driver: { id: 306, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, time_or_gap: "+27.092", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, lap_time: "1:31.869", lap_number: 35 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:33:19.273" },
      { position: 2, driver: { id: 401, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 18, time_or_gap: "+3.264" },
      { position: 3, driver: { id: 402, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 15, time_or_gap: "+27.092" },
      { position: 4, driver: { id: 403, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 12, time_or_gap: "+43.051" },
      { position: 5, driver: { id: 404, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 10, time_or_gap: "+48.949" },
      { position: 6, driver: { id: 405, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 8, time_or_gap: "+53.753" },
      { position: 7, driver: { id: 406, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+1:01.871" },
      { position: 8, driver: { id: 407, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 4, time_or_gap: "+1:04.245" },
      { position: 9, driver: { id: 408, driver_number: 55, broadcast_name: "C. SAINZ", full_name: "Carlos Sainz", team_name: "Williams", color_hex: getTeamColorHex("Williams"), country_code: "SPA" }, team_name: "Williams", team_color: getTeamColorHex("Williams"), points: 2, time_or_gap: "+1:22.072" },
      { position: 10, driver: { id: 409, driver_number: 23, broadcast_name: "A. ALBON", full_name: "Alexander Albon", team_name: "Williams", color_hex: getTeamColorHex("Williams"), country_code: "THA" }, team_name: "Williams", team_color: getTeamColorHex("Williams"), points: 1, time_or_gap: "+1:30.972" },
    ],
  },
  7: {
    race_id: 7,
    season: 2026,
    round_number: 7,
    race_name: "Canadian Grand Prix",
    circuit_name: "Circuit Gilles Villeneuve",
    country: "Canada",
    country_code: "CAN",
    date: "2026-05-24",
    status: 'COMPLETED',
    laps_completed: 68,
    total_laps: 68,
    podium: {
      p1: { position: 1, driver: { id: 107, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:28:15.758", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 207, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, time_or_gap: "+10.768", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 307, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+11.276", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:14.210", lap_number: 68 },
    pole_position: { driver: { id: 998, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:28:15.758" },
      { position: 2, driver: { id: 401, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 18, time_or_gap: "+10.768" },
      { position: 3, driver: { id: 402, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 15, time_or_gap: "+11.276" },
      { position: 4, driver: { id: 403, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+44.151" },
      { position: 5, driver: { id: 404, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 10, time_or_gap: "+5.033" },
      { position: 6, driver: { id: 405, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 8, time_or_gap: "+19.510" },
      { position: 7, driver: { id: 406, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 6, time_or_gap: "+34.235" },
      { position: 8, driver: { id: 407, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 4, time_or_gap: "+34.572" },
      { position: 9, driver: { id: 408, driver_number: 55, broadcast_name: "C. SAINZ", full_name: "Carlos Sainz", team_name: "Williams", color_hex: getTeamColorHex("Williams"), country_code: "SPA" }, team_name: "Williams", team_color: getTeamColorHex("Williams"), points: 2, time_or_gap: "+58.014" },
      { position: 10, driver: { id: 409, driver_number: 87, broadcast_name: "O. BEARMAN", full_name: "Oliver Bearman", team_name: "Haas F1 Team", color_hex: getTeamColorHex("Haas F1 Team"), country_code: "BRI" }, team_name: "Haas F1 Team", team_color: getTeamColorHex("Haas F1 Team"), points: 1, time_or_gap: "+59.049" },
    ],
  },
  8: {
    race_id: 8,
    season: 2026,
    round_number: 8,
    race_name: "Monaco Grand Prix",
    circuit_name: "Circuit de Monaco",
    country: "Monaco",
    country_code: "MON",
    date: "2026-06-07",
    status: 'COMPLETED',
    laps_completed: 78,
    total_laps: 78,
    podium: {
      p1: { position: 1, driver: { id: 108, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "2:23:31.243", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 208, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, time_or_gap: "+6.271", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 308, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, time_or_gap: "+23.394", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:13.481", lap_number: 76 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "2:23:31.243" },
      { position: 2, driver: { id: 401, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 18, time_or_gap: "+6.271" },
      { position: 3, driver: { id: 402, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 15, time_or_gap: "+23.394" },
      { position: 4, driver: { id: 403, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 12, time_or_gap: "+24.261" },
      { position: 5, driver: { id: 404, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 10, time_or_gap: "+26.553" },
      { position: 6, driver: { id: 405, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 8, time_or_gap: "+29.010" },
      { position: 7, driver: { id: 406, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+30.369" },
      { position: 8, driver: { id: 407, driver_number: 23, broadcast_name: "A. ALBON", full_name: "Alexander Albon", team_name: "Williams", color_hex: getTeamColorHex("Williams"), country_code: "THA" }, team_name: "Williams", team_color: getTeamColorHex("Williams"), points: 4, time_or_gap: "+33.413" },
      { position: 9, driver: { id: 408, driver_number: 31, broadcast_name: "E. OCON", full_name: "Esteban Ocon", team_name: "Haas F1 Team", color_hex: getTeamColorHex("Haas F1 Team"), country_code: "FRE" }, team_name: "Haas F1 Team", team_color: getTeamColorHex("Haas F1 Team"), points: 2, time_or_gap: "+37.140" },
      { position: 10, driver: { id: 409, driver_number: 14, broadcast_name: "F. ALONSO", full_name: "Fernando Alonso", team_name: "Aston Martin", color_hex: getTeamColorHex("Aston Martin"), country_code: "SPA" }, team_name: "Aston Martin", team_color: getTeamColorHex("Aston Martin"), points: 1, time_or_gap: "+41.899" },
    ],
  },
  9: {
    race_id: 9,
    season: 2026,
    round_number: 9,
    race_name: "Barcelona Grand Prix",
    circuit_name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    country_code: "SPA",
    date: "2026-06-14",
    status: 'COMPLETED',
    laps_completed: 66,
    total_laps: 66,
    podium: {
      p1: { position: 1, driver: { id: 109, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, time_or_gap: "1:32:28.105", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 209, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "+19.561", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 309, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, time_or_gap: "+23.719", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, lap_time: "1:20.122", lap_number: 44 },
    pole_position: { driver: { id: 998, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 25, time_or_gap: "1:32:28.105" },
      { position: 2, driver: { id: 401, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+19.561" },
      { position: 3, driver: { id: 402, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 15, time_or_gap: "+23.719" },
      { position: 4, driver: { id: 403, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 12, time_or_gap: "+40.497" },
      { position: 5, driver: { id: 404, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 10, time_or_gap: "+58.661" },
      { position: 6, driver: { id: 405, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+24.627" },
      { position: 7, driver: { id: 406, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+55.789" },
      { position: 8, driver: { id: 407, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 4, time_or_gap: "+1:12.224" },
      { position: 9, driver: { id: 408, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 2, time_or_gap: "+1:18.074" },
      { position: 10, driver: { id: 409, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+1:19.867" },
    ],
  },
  10: {
    race_id: 10,
    season: 2026,
    round_number: 10,
    race_name: "Austrian Grand Prix",
    circuit_name: "Red Bull Ring",
    country: "Austria",
    country_code: "AUS",
    date: "2026-06-28",
    status: 'COMPLETED',
    laps_completed: 71,
    total_laps: 71,
    podium: {
      p1: { position: 1, driver: { id: 110, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "1:26:37.979", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 210, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+1.611", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 310, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "+1.986", points: 15, fastest_lap: true },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:10.374", lap_number: 59 },
    pole_position: { driver: { id: 998, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:26:37.979" },
      { position: 2, driver: { id: 401, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 18, time_or_gap: "+1.611" },
      { position: 3, driver: { id: 402, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 15, time_or_gap: "+1.986" },
      { position: 4, driver: { id: 403, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 12, time_or_gap: "+21.809" },
      { position: 5, driver: { id: 404, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 10, time_or_gap: "+26.393" },
      { position: 6, driver: { id: 405, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+29.399" },
      { position: 7, driver: { id: 406, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 6, time_or_gap: "+31.505" },
      { position: 8, driver: { id: 407, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 4, time_or_gap: "+45.659" },
      { position: 9, driver: { id: 408, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 2, time_or_gap: "+15.334" },
      { position: 10, driver: { id: 409, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 1, time_or_gap: "+19.030" },
    ],
  },
  11: {
    race_id: 11,
    season: 2026,
    round_number: 11,
    race_name: "British Grand Prix",
    circuit_name: "Silverstone Circuit",
    country: "UK",
    country_code: "UK",
    date: "2026-07-05",
    status: 'COMPLETED',
    laps_completed: 52,
    total_laps: 52,
    podium: {
      p1: { position: 1, driver: { id: 111, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, time_or_gap: "1:27:11.335", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 211, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "+0.427", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 311, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, time_or_gap: "+0.772", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:31.777", lap_number: 37 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 25, time_or_gap: "1:27:11.335" },
      { position: 2, driver: { id: 401, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+0.427" },
      { position: 3, driver: { id: 402, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 15, time_or_gap: "+0.772" },
      { position: 4, driver: { id: 403, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 12, time_or_gap: "+1.149" },
      { position: 5, driver: { id: 404, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 10, time_or_gap: "+1.598" },
      { position: 6, driver: { id: 405, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 8, time_or_gap: "+2.023" },
      { position: 7, driver: { id: 406, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 6, time_or_gap: "+2.214" },
      { position: 8, driver: { id: 407, driver_number: 5, broadcast_name: "G. BORTOLETO", full_name: "Gabriel Bortoleto", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "BRA" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 4, time_or_gap: "+2.413" },
      { position: 9, driver: { id: 408, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 2, time_or_gap: "+3.229" },
      { position: 10, driver: { id: 409, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+3.445" },
    ],
  },
  12: {
    race_id: 12,
    season: 2026,
    round_number: 12,
    race_name: "Belgian Grand Prix",
    circuit_name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    country_code: "BEL",
    date: "2026-07-19",
    status: 'COMPLETED',
    laps_completed: 44,
    total_laps: 44,
    podium: {
      p1: { position: 1, driver: { id: 112, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:24:42.479", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 212, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, time_or_gap: "+1.952", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 312, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+11.586", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, lap_time: "1:48.890", lap_number: 44 },
    pole_position: { driver: { id: 998, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:24:42.479" },
      { position: 2, driver: { id: 401, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 18, time_or_gap: "+1.952" },
      { position: 3, driver: { id: 402, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 15, time_or_gap: "+11.586" },
      { position: 4, driver: { id: 403, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+17.245" },
      { position: 5, driver: { id: 404, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 10, time_or_gap: "+18.988" },
      { position: 6, driver: { id: 405, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+23.307" },
      { position: 7, driver: { id: 406, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 6, time_or_gap: "+24.014" },
      { position: 8, driver: { id: 407, driver_number: 5, broadcast_name: "G. BORTOLETO", full_name: "Gabriel Bortoleto", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "BRA" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 4, time_or_gap: "+49.140" },
      { position: 9, driver: { id: 408, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 2, time_or_gap: "+50.406" },
      { position: 10, driver: { id: 409, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+1:16.037" },
    ],
  },
  13: {
    race_id: 13,
    season: 2026,
    round_number: 13,
    race_name: "Hungarian Grand Prix",
    circuit_name: "Hungaroring",
    country: "Hungary",
    country_code: "HUN",
    date: "2026-07-26",
    status: 'COMPLETED',
    laps_completed: 70,
    total_laps: 70,
    podium: {
      p1: { position: 1, driver: { id: 113, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, time_or_gap: "1:39:56.180", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 213, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+15.080", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 313, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "+18.728", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, lap_time: "1:22.000", lap_number: 58 },
    pole_position: { driver: { id: 998, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 25, time_or_gap: "1:39:56.180" },
      { position: 2, driver: { id: 401, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 18, time_or_gap: "+15.080" },
      { position: 3, driver: { id: 402, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 15, time_or_gap: "+18.728" },
      { position: 4, driver: { id: 403, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+23.840" },
      { position: 5, driver: { id: 404, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 10, time_or_gap: "+24.540" },
      { position: 6, driver: { id: 405, driver_number: 6, broadcast_name: "I. HADJAR", full_name: "Isack Hadjar", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "FRE" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+55.488" },
      { position: 7, driver: { id: 406, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 6, time_or_gap: "+57.503" },
      { position: 8, driver: { id: 407, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "NEW" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 4, time_or_gap: "+28.033" },
      { position: 9, driver: { id: 408, driver_number: 27, broadcast_name: "N. HÜLKENBERG", full_name: "Nico Hülkenberg", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "GER" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 2, time_or_gap: "+30.382" },
      { position: 10, driver: { id: 409, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 1, time_or_gap: "+51.050" },
    ],
  },
  14: {
    race_id: 14,
    season: 2026,
    round_number: 14,
    race_name: "Dutch Grand Prix",
    circuit_name: "Circuit Park Zandvoort",
    country: "Netherlands",
    country_code: "NET",
    date: "2026-08-23",
    status: 'COMPLETED',
    laps_completed: 72,
    total_laps: 72,
    podium: {
      p1: { position: 1, driver: { id: 114, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, time_or_gap: "2:04:44.859", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 214, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "+11.536", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 314, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "+15.906", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, lap_time: "1:14.230", lap_number: 60 },
    pole_position: { driver: { id: 998, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 25, time_or_gap: "2:04:44.859" },
      { position: 2, driver: { id: 401, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+11.536" },
      { position: 3, driver: { id: 402, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 15, time_or_gap: "+15.906" },
      { position: 4, driver: { id: 403, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+16.755" },
      { position: 5, driver: { id: 404, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 10, time_or_gap: "+17.258" },
      { position: 6, driver: { id: 405, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 8, time_or_gap: "+32.332" },
      { position: 7, driver: { id: 406, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "NEW" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 6, time_or_gap: "+1:19.915" },
      { position: 8, driver: { id: 407, driver_number: 27, broadcast_name: "N. HÜLKENBERG", full_name: "Nico Hülkenberg", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "GER" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 4, time_or_gap: "+36.049" },
      { position: 9, driver: { id: 408, driver_number: 14, broadcast_name: "F. ALONSO", full_name: "Fernando Alonso", team_name: "Aston Martin", color_hex: getTeamColorHex("Aston Martin"), country_code: "SPA" }, team_name: "Aston Martin", team_color: getTeamColorHex("Aston Martin"), points: 2, time_or_gap: "+48.393" },
      { position: 10, driver: { id: 409, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 1, time_or_gap: "+49.640" },
    ],
  },
  15: {
    race_id: 15,
    season: 2026,
    round_number: 15,
    race_name: "Italian Grand Prix",
    circuit_name: "Autodromo Nazionale di Monza",
    country: "Italy",
    country_code: "ITA",
    date: "2026-09-06",
    status: 'COMPLETED',
    laps_completed: 53,
    total_laps: 53,
    podium: {
      p1: { position: 1, driver: { id: 115, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:51:15.281", points: 25, fastest_lap: true },
      p2: { position: 2, driver: { id: 215, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, time_or_gap: "+3.857", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 315, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+14.718", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, lap_time: "1:23.504", lap_number: 53 },
    pole_position: { driver: { id: 998, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:51:15.281" },
      { position: 2, driver: { id: 401, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 18, time_or_gap: "+3.857" },
      { position: 3, driver: { id: 402, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 15, time_or_gap: "+14.718" },
      { position: 4, driver: { id: 403, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 12, time_or_gap: "+19.056" },
      { position: 5, driver: { id: 404, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 10, time_or_gap: "+19.253" },
      { position: 6, driver: { id: 405, driver_number: 44, broadcast_name: "L. HAMILTON", full_name: "Lewis Hamilton", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "BRI" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 8, time_or_gap: "+24.655" },
      { position: 7, driver: { id: 406, driver_number: 10, broadcast_name: "P. GASLY", full_name: "Pierre Gasly", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "FRE" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+27.351" },
      { position: 8, driver: { id: 407, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 4, time_or_gap: "+45.136" },
      { position: 9, driver: { id: 408, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 2, time_or_gap: "+47.353" },
      { position: 10, driver: { id: 409, driver_number: 22, broadcast_name: "Y. TSUNODA", full_name: "Yuki Tsunoda", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "JAP" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 1, time_or_gap: "+58.187" },
    ],
  },
  16: {
    race_id: 16,
    season: 2026,
    round_number: 16,
    race_name: "Spanish Grand Prix",
    circuit_name: "Madring",
    country: "Spain",
    country_code: "SPA",
    date: "2026-09-13",
    status: 'COMPLETED',
    laps_completed: 57,
    total_laps: 57,
    podium: {
      p1: { position: 1, driver: { id: 116, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, time_or_gap: "1:34:23.754", points: 25, fastest_lap: false },
      p2: { position: 2, driver: { id: 216, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, time_or_gap: "+4.351", points: 18, fastest_lap: false },
      p3: { position: 3, driver: { id: 316, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, time_or_gap: "+5.089", points: 15, fastest_lap: false },
    },
    fastest_lap: { driver: { id: 999, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, lap_time: "1:35.587", lap_number: 49 },
    pole_position: { driver: { id: 998, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, q3_time: '1:18.500' },
    top_finishers: [
      { position: 1, driver: { id: 400, driver_number: 12, broadcast_name: "A. ANTONELLI", full_name: "Andrea Kimi Antonelli", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "ITA" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 25, time_or_gap: "1:34:23.754" },
      { position: 2, driver: { id: 401, driver_number: 3, broadcast_name: "M. VERSTAPPEN", full_name: "Max Verstappen", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "DUT" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 18, time_or_gap: "+4.351" },
      { position: 3, driver: { id: 402, driver_number: 1, broadcast_name: "L. NORRIS", full_name: "Lando Norris", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "BRI" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 15, time_or_gap: "+5.089" },
      { position: 4, driver: { id: 403, driver_number: 16, broadcast_name: "C. LECLERC", full_name: "Charles Leclerc", team_name: "Ferrari", color_hex: getTeamColorHex("Ferrari"), country_code: "MON" }, team_name: "Ferrari", team_color: getTeamColorHex("Ferrari"), points: 12, time_or_gap: "+29.116" },
      { position: 5, driver: { id: 404, driver_number: 63, broadcast_name: "G. RUSSELL", full_name: "George Russell", team_name: "Mercedes", color_hex: getTeamColorHex("Mercedes"), country_code: "BRI" }, team_name: "Mercedes", team_color: getTeamColorHex("Mercedes"), points: 10, time_or_gap: "+29.829" },
      { position: 6, driver: { id: 405, driver_number: 30, broadcast_name: "L. LAWSON", full_name: "Liam Lawson", team_name: "Red Bull", color_hex: getTeamColorHex("Red Bull"), country_code: "NEW" }, team_name: "Red Bull", team_color: getTeamColorHex("Red Bull"), points: 8, time_or_gap: "+1:26.746" },
      { position: 7, driver: { id: 406, driver_number: 43, broadcast_name: "F. COLAPINTO", full_name: "Franco Colapinto", team_name: "Alpine F1 Team", color_hex: getTeamColorHex("Alpine F1 Team"), country_code: "ARG" }, team_name: "Alpine F1 Team", team_color: getTeamColorHex("Alpine F1 Team"), points: 6, time_or_gap: "+1:34.281" },
      { position: 8, driver: { id: 407, driver_number: 81, broadcast_name: "O. PIASTRI", full_name: "Oscar Piastri", team_name: "McLaren", color_hex: getTeamColorHex("McLaren"), country_code: "AUS" }, team_name: "McLaren", team_color: getTeamColorHex("McLaren"), points: 4, time_or_gap: "+1:35.839" },
      { position: 9, driver: { id: 408, driver_number: 41, broadcast_name: "A. LINDBLAD", full_name: "Arvid Lindblad", team_name: "RB F1 Team", color_hex: getTeamColorHex("RB F1 Team"), country_code: "BRI" }, team_name: "RB F1 Team", team_color: getTeamColorHex("RB F1 Team"), points: 2, time_or_gap: "+10.408" },
      { position: 10, driver: { id: 409, driver_number: 27, broadcast_name: "N. HÜLKENBERG", full_name: "Nico Hülkenberg", team_name: "Audi", color_hex: getTeamColorHex("Audi"), country_code: "GER" }, team_name: "Audi", team_color: getTeamColorHex("Audi"), points: 1, time_or_gap: "+11.298" },
    ],
  },
};
