import os, json, xml.etree.ElementTree as ET
import numpy as np
from generate_dataset_helpers import extract_track_points_and_sf
from scipy.signal import find_peaks

CIRCUITS_META = [
    {
        "id": 1,
        "svg_file": "monza.svg",
        "circuit_name": "Autodromo Nazionale Monza",
        "location": "Monza",
        "country": "Italy",
        "country_code": "ITA",
        "lat": 45.6189,
        "lng": 9.2811,
        "length_km": 5.793,
        "corners_count": 11,
        "drs_zones": 2,
        "lap_record": "1:21.046",
        "lap_record_driver": "Rubens Barrichello",
        "lap_record_year": 2004,
        "lap_record_team": "Ferrari F2004",
        "full_throttle_pct": 76,
        "downforce_level": "ULTRA-LOW",
        "tyre_stress_level": 4,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 42,
        "pit_loss_time_sec": 24.1,
        "first_grand_prix_year": 1950,
        "elevation_gain_m": 12.8,
        "description": "The Temple of Speed. Featuring the highest average speeds on the calendar with slipstreaming down the Rettifilo and maximum braking loads.",
        "corner_names": [
            ("Variante del Rettifilo (T1)", 2, 74, 2.1, True, False, "Extreme braking from 345 km/h at end of pit straight"),
            ("Variante del Rettifilo (T2)", 2, 85, 2.3, False, False, "Right turn exit onto Curva Grande"),
            ("Curva Grande (Biassono)", 7, 290, 3.8, False, False, "Full throttle high-speed sweep"),
            ("Variante della Roggia (T4)", 3, 118, 2.6, True, False, "Aggressive left kerb usage required"),
            ("Variante della Roggia (T5)", 3, 130, 2.8, False, False, "Right exit towards Lesmo"),
            ("Curva di Lesmo 1 (T6)", 4, 172, 3.4, False, False, "Blind turn-in apex"),
            ("Curva di Lesmo 2 (T7)", 4, 156, 3.1, False, False, "Crucial exit traction towards Serraglio"),
            ("Variante Ascari (T8)", 4, 168, 4.1, True, False, "Triple chicane left entry"),
            ("Variante Ascari (T9)", 4, 195, 4.3, False, False, "Right middle flick"),
            ("Variante Ascari (T10)", 5, 220, 3.9, False, False, "Left launch onto back straight"),
            ("Curva Parabolica / Alboreto", 5, 182, 3.6, False, True, "Long parabolic corner onto main straight")
        ]
    },
    {
        "id": 2,
        "svg_file": "spa.svg",
        "circuit_name": "Circuit de Spa-Francorchamps",
        "location": "Stavelot",
        "country": "Belgium",
        "country_code": "BEL",
        "lat": 50.4372,
        "lng": 5.9714,
        "length_km": 7.004,
        "corners_count": 19,
        "drs_zones": 2,
        "lap_record": "1:46.286",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2018,
        "lap_record_team": "Mercedes W09",
        "full_throttle_pct": 70,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 5,
        "brake_wear_index": "MODERATE",
        "gear_shifts_per_lap": 58,
        "pit_loss_time_sec": 22.8,
        "first_grand_prix_year": 1950,
        "elevation_gain_m": 102.2,
        "description": "The Ardennes roller-coaster. World-famous for Eau Rouge / Raidillon compression, high lateral loadings through Pouhon, and changeable micro-climates.",
        "corner_names": [
            ("La Source", 1, 68, 2.0, True, False, "Hairpin turn leading to Eau Rouge plunge"),
            ("Eau Rouge (Entry)", 7, 300, 3.5, False, False, "Steep downhill left"),
            ("Eau Rouge (Compression)", 8, 305, 4.8, False, False, "Maximum vertical 3G compression"),
            ("Raidillon (Crest)", 8, 310, 4.2, False, False, "Blind uphill crest launch onto Kemmel"),
            ("Les Combes (T5)", 3, 135, 2.8, True, False, "Right entry chicane at end of Kemmel"),
            ("Les Combes (T6)", 3, 145, 3.0, False, False, "Left transition"),
            ("Malmedy", 4, 180, 3.3, False, False, "Fast right exit"),
            ("Rivage (Bruxelles)", 2, 105, 2.4, True, False, "Downhill 180-degree right hairpin"),
            ("Speakers Corner", 4, 160, 3.1, False, False, "Left downhill plunge"),
            ("Pouhon (Apex 1)", 6, 260, 4.6, False, False, "High-speed double left with massive lateral G"),
            ("Pouhon (Apex 2)", 6, 270, 4.4, False, False, "Second apex acceleration"),
            ("Fagnes (Entry)", 4, 165, 3.2, False, False, "Right turn entry"),
            ("Fagnes (Exit)", 4, 175, 3.4, False, False, "Left turn exit"),
            ("Campus", 5, 210, 3.2, False, False, "Fast right sweeper"),
            ("Stavelot", 5, 230, 3.6, False, False, "Entry onto Blanchimont flat-out sprint"),
            ("Courbe Paul Frère", 7, 290, 3.5, False, False, "High-speed kink"),
            ("Blanchimont", 8, 315, 3.7, False, False, "Flat-out kink before Bus Stop"),
            ("Bus Stop Chicane (T18)", 2, 75, 2.2, True, False, "Heavy deceleration right"),
            ("Bus Stop Chicane (T19)", 2, 90, 2.3, False, True, "Tight left onto start straight")
        ]
    },
    {
        "id": 3,
        "svg_file": "silverstone.svg",
        "circuit_name": "Silverstone Circuit",
        "location": "Silverstone",
        "country": "United Kingdom",
        "country_code": "GBR",
        "lat": 52.0786,
        "lng": -1.0169,
        "length_km": 5.891,
        "corners_count": 18,
        "drs_zones": 2,
        "lap_record": "1:27.097",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2020,
        "lap_record_team": "Red Bull RB16",
        "full_throttle_pct": 68,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "LOW",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 25.4,
        "first_grand_prix_year": 1950,
        "elevation_gain_m": 11.3,
        "description": "The Home of British Motor Racing. High-speed aerodynamic benchmark featuring the iconic Maggotts-Becketts-Chapel complex and Copse.",
        "corner_names": [
            ("Abbey", 7, 285, 4.2, False, False, "Fast right-hander off the start line"),
            ("Farm Curve", 7, 290, 3.8, False, False, "Left sweep towards Village"),
            ("Village", 2, 88, 2.2, True, False, "Heavy deceleration right hairpin"),
            ("The Loop", 2, 75, 1.9, True, False, "Tight left hairpin"),
            ("Aintree", 3, 135, 2.7, False, False, "Exit onto Wellington Straight"),
            ("Brooklands", 4, 155, 3.1, False, False, "Left sweeper into Luffield"),
            ("Luffield", 2, 92, 2.3, True, False, "Long parabolic right"),
            ("Woodcote", 5, 215, 3.4, False, False, "Right sweep onto National Straight"),
            ("Copse", 8, 290, 4.9, False, False, "One of the fastest corners in world motorsport"),
            ("Maggotts", 8, 295, 5.0, False, False, "Entry to apex sequence"),
            ("Becketts (Entry)", 7, 265, 4.8, False, False, "High-speed left flick"),
            ("Becketts (Apex)", 6, 240, 4.5, False, False, "Rapid direction change testing front-end grip"),
            ("Becketts (Exit)", 6, 250, 4.1, False, False, "Left exit transition"),
            ("Chapel", 7, 275, 3.6, False, True, "Exit onto Hangar Straight"),
            ("Stowe", 5, 200, 3.5, True, False, "Heavy braking zone at end of Hangar Straight"),
            ("Vale", 2, 85, 2.1, True, False, "Tight left-right before Club"),
            ("Club (Entry)", 4, 165, 2.9, False, False, "First apex right"),
            ("Club (Exit)", 5, 195, 3.4, False, False, "Double right onto Hamilton Straight")
        ]
    },
    {
        "id": 4,
        "svg_file": "monaco.svg",
        "circuit_name": "Circuit de Monaco",
        "location": "Monte Carlo",
        "country": "Monaco",
        "country_code": "MON",
        "lat": 43.7347,
        "lng": 7.4206,
        "length_km": 3.337,
        "corners_count": 19,
        "drs_zones": 1,
        "lap_record": "1:12.909",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "lap_record_team": "Mercedes W12",
        "full_throttle_pct": 34,
        "downforce_level": "MAXIMUM",
        "tyre_stress_level": 1,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 54,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 1950,
        "elevation_gain_m": 42.0,
        "description": "The Jewel in the Crown. Tight barriers, zero room for error, requiring maximum mechanical downforce, steering angle, and driver precision.",
        "corner_names": [
            ("Sainte Dévote", 2, 88, 2.1, True, False, "Right-hander into Beau Rivage hill"),
            ("Beau Rivage", 6, 260, 2.8, False, False, "Uphill sweeping straight"),
            ("Massenet", 4, 155, 3.4, False, False, "Long left around the crest"),
            ("Casino Square", 4, 150, 2.9, False, False, "Blind crest left over the bump"),
            ("Mirabeau Haute", 2, 90, 2.2, True, False, "Downhill right-hander"),
            ("Grand Hotel Hairpin", 1, 46, 1.4, True, False, "Slowest corner in Formula 1 (46 km/h)"),
            ("Mirabeau Bas", 2, 82, 2.0, False, False, "Tight right turn"),
            ("Portier", 2, 75, 1.9, False, False, "Entry onto waterfront and Tunnel"),
            ("Tunnel", 7, 285, 3.1, False, False, "Light change on blind downhill exit"),
            ("Nouvelle Chicane (T10)", 2, 65, 2.3, True, False, "Prime overtaking opportunity"),
            ("Nouvelle Chicane (T11)", 2, 85, 2.1, False, False, "Launch onto harbour quayside"),
            ("Tabac", 4, 165, 3.6, False, False, "High commitment portside left"),
            ("Louis Chiron (Entry)", 5, 215, 4.1, False, False, "Fast chicane clipping inside barrier"),
            ("Louis Chiron (Exit)", 5, 205, 3.8, False, False, "Swimming pool entry"),
            ("Swimming Pool (Entry)", 3, 125, 2.9, True, False, "Tight right kerb chicane"),
            ("Swimming Pool (Exit)", 3, 140, 3.1, False, False, "Tight left exit"),
            ("La Rascasse (Entry)", 2, 60, 1.7, True, False, "Tight right around restaurant"),
            ("La Rascasse (Apex)", 2, 70, 1.8, False, False, "Hairpin apex"),
            ("Anthony Noghès", 3, 105, 2.4, False, True, "Right turn onto pit straight")
        ]
    },
    {
        "id": 5,
        "svg_file": "suzuka.svg",
        "circuit_name": "Suzuka International Racing Course",
        "location": "Suzuka",
        "country": "Japan",
        "country_code": "JPN",
        "lat": 34.8431,
        "lng": 136.5411,
        "length_km": 5.807,
        "corners_count": 18,
        "drs_zones": 1,
        "lap_record": "1:30.983",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2019,
        "lap_record_team": "Mercedes W10",
        "full_throttle_pct": 65,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "LOW",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 23.2,
        "first_grand_prix_year": 1987,
        "elevation_gain_m": 40.4,
        "description": "The Ultimate Drivers Circuit. The only figure-eight layout in F1, demanding perfect balance through the S-Curves, Degner, Spoon, and flat-out 130R.",
        "corner_names": [
            ("Turn 1", 5, 220, 3.6, False, False, "Fast right entry into T2 deceleration"),
            ("Turn 2", 3, 130, 2.7, True, False, "Tight right leading to Esses"),
            ("S Curves (T3)", 5, 210, 4.3, False, False, "Left entry into flowing snake"),
            ("S Curves (T4)", 5, 195, 4.4, False, False, "Right transition"),
            ("S Curves (T5)", 5, 185, 4.2, False, False, "Left uphill flick"),
            ("S Curves (T6)", 5, 190, 4.0, False, False, "Right climb towards Dunlop"),
            ("Dunlop Curve", 6, 240, 3.8, False, False, "Long uphill blind left"),
            ("Degner 1", 6, 255, 4.5, False, False, "Fast right turn-in clipping inside kerb"),
            ("Degner 2", 3, 135, 2.9, True, False, "Tight right under bridge; punishing gravel on exit"),
            ("Turn 10", 7, 275, 3.5, False, False, "Underpass sweep"),
            ("Hairpin (T11)", 2, 70, 1.8, True, False, "Heavy braking tight left hairpin"),
            ("Turn 12", 7, 280, 3.2, False, False, "Flat out kink before Spoon"),
            ("Spoon Curve (Entry)", 4, 180, 3.6, True, False, "Downhill left apex"),
            ("Spoon Curve (Exit)", 5, 205, 3.4, False, False, "Wide launch onto the Crossover Straight"),
            ("130R (T15)", 8, 305, 4.7, False, False, "Iconic flat-out 300+ km/h left curve"),
            ("Casio Triangle (T16)", 2, 80, 2.2, True, False, "Chicane right entry"),
            ("Casio Triangle (T17)", 2, 95, 2.4, False, False, "Left exit"),
            ("Turn 18", 6, 220, 3.2, False, True, "Right sweep onto main straight")
        ]
    },
    {
        "id": 6,
        "svg_file": "interlagos.svg",
        "circuit_name": "Autódromo José Carlos Pace (Interlagos)",
        "location": "São Paulo",
        "country": "Brazil",
        "country_code": "BRA",
        "lat": -23.7036,
        "lng": -46.6997,
        "length_km": 4.309,
        "corners_count": 15,
        "drs_zones": 2,
        "lap_record": "1:10.540",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2018,
        "lap_record_team": "Mercedes W09",
        "full_throttle_pct": 60,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "MODERATE",
        "gear_shifts_per_lap": 42,
        "pit_loss_time_sec": 22.4,
        "first_grand_prix_year": 1973,
        "elevation_gain_m": 43.0,
        "description": "Atmospheric amphitheatre running anti-clockwise. Famous for the Senna S downhill chicane, Junção uphill drag, and unpredictable tropical storms.",
        "corner_names": [
            ("Senna S (T1)", 3, 115, 2.6, True, False, "Downhill left blind apex into Senna S"),
            ("Senna S (T2)", 3, 130, 2.8, False, False, "Right transition"),
            ("Curva do Sol (T3)", 5, 220, 3.5, False, False, "Long left onto Reta Oposta"),
            ("Descida do Lago (T4)", 4, 155, 3.2, True, False, "Left entry at end of DRS straight"),
            ("Descida do Lago (T5)", 4, 175, 3.4, False, False, "Right exit acceleration"),
            ("Ferradura (T6)", 5, 210, 3.6, False, False, "Long uphill double-apex right"),
            ("Ferradura (T7)", 5, 225, 3.5, False, False, "Second apex right"),
            ("Curva do Laranjinha", 4, 170, 3.1, False, False, "Blind right over the crest"),
            ("Pinheirinho", 2, 90, 2.1, True, False, "Tight downhill left"),
            ("Bico de Pato", 2, 78, 1.9, True, False, "Duck's beak right hairpin"),
            ("Mergulho", 5, 220, 3.8, False, False, "Fast left compression plunge"),
            ("Junção", 3, 125, 2.5, True, False, "Critical left apex onto uphill climb"),
            ("Subida dos Boxes", 6, 255, 3.2, False, False, "Uphill full throttle drag"),
            ("Curva dos Boxes", 7, 280, 3.0, False, False, "Left sweep passing pit lane entry"),
            ("Arquibancadas", 8, 305, 3.1, False, True, "Full throttle launch onto main straight")
        ]
    },
    {
        "id": 7,
        "svg_file": "marina_bay.svg",
        "circuit_name": "Marina Bay Street Circuit",
        "location": "Singapore",
        "country": "Singapore",
        "country_code": "SGP",
        "lat": 1.2914,
        "lng": 103.864,
        "length_km": 4.940,
        "corners_count": 19,
        "drs_zones": 4,
        "lap_record": "1:35.867",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2023,
        "lap_record_team": "Mercedes W14",
        "full_throttle_pct": 52,
        "downforce_level": "MAXIMUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 64,
        "pit_loss_time_sec": 28.5,
        "first_grand_prix_year": 2008,
        "elevation_gain_m": 6.8,
        "description": "F1 original night race. Punishing tropical humidity, 19 corners between the barriers, and relentless physical demands on drivers and brakes.",
        "corner_names": [
            ("Sheares (T1)", 3, 120, 2.5, True, False, "Left entry at end of pit straight"),
            ("Turn 2", 3, 110, 2.3, False, False, "Right transition"),
            ("Turn 3", 2, 85, 2.0, True, False, "Tight left onto Republic Boulevard"),
            ("Turn 4", 5, 205, 3.1, False, False, "Right sweep"),
            ("Turn 5", 4, 140, 2.7, False, False, "Right onto Raffles Boulevard straight"),
            ("Turn 6", 7, 280, 3.2, False, False, "Flat-out left kink"),
            ("Memorial (T7)", 2, 85, 2.2, True, False, "90-degree left at end of Raffles straight"),
            ("Turn 8", 3, 115, 2.4, False, False, "Right turn towards Stamford Road"),
            ("Turn 9", 3, 120, 2.5, False, False, "Left turn onto St Andrews Road"),
            ("Turn 10", 4, 155, 2.9, False, False, "Left sweeper by the Padang"),
            ("Turn 11", 3, 130, 2.6, False, False, "Right kink onto Anderson Bridge"),
            ("Turn 12", 4, 160, 2.8, False, False, "Anderson Bridge exit"),
            ("Turn 13", 2, 65, 1.8, True, False, "Tight left hairpin onto Esplanade Drive"),
            ("Turn 14", 3, 105, 2.4, True, False, "90-degree right at end of Esplanade"),
            ("Turn 15", 5, 210, 3.0, False, False, "Fast sweeper under new layout straight"),
            ("Turn 16", 4, 150, 2.8, True, False, "Chicane left entry"),
            ("Turn 17", 4, 145, 2.7, False, False, "Chicane right exit"),
            ("Turn 18", 4, 165, 3.0, False, False, "Left sweeper under grandstand"),
            ("Turn 19", 5, 190, 3.2, False, True, "Fast left onto pit straight")
        ]
    },
    {
        "id": 8,
        "svg_file": "baku.svg",
        "circuit_name": "Baku City Circuit",
        "location": "Baku",
        "country": "Azerbaijan",
        "country_code": "AZE",
        "lat": 40.3725,
        "lng": 49.8533,
        "length_km": 6.003,
        "corners_count": 20,
        "drs_zones": 2,
        "lap_record": "1:43.009",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2019,
        "lap_record_team": "Ferrari SF90",
        "full_throttle_pct": 56,
        "downforce_level": "LOW",
        "tyre_stress_level": 2,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 62,
        "pit_loss_time_sec": 24.8,
        "first_grand_prix_year": 2016,
        "elevation_gain_m": 26.5,
        "description": "City of Winds. Unites a 2.2km flat-out blast along the Caspian Sea with the ultra-narrow 7.6m Medieval Castle section.",
        "corner_names": [
            ("Turn 1", 2, 95, 2.4, True, False, "90-degree left from 350 km/h braking zone"),
            ("Turn 2", 2, 90, 2.3, True, False, "90-degree left onto straight"),
            ("Turn 3", 3, 115, 2.5, True, False, "90-degree left"),
            ("Turn 4", 3, 120, 2.6, False, False, "90-degree right onto street boulevard"),
            ("Turn 5", 2, 95, 2.3, True, False, "Right entry into tight square"),
            ("Turn 6", 2, 90, 2.2, False, False, "Left exit"),
            ("Turn 7", 2, 85, 2.1, True, False, "Heavy braking right"),
            ("Castle Section (T8)", 1, 65, 1.8, False, False, "Narrowest point on calendar (7.6m width)"),
            ("Castle Section (T9)", 2, 80, 2.0, False, False, "Right kink climbing around fortress wall"),
            ("Castle Section (T10)", 2, 85, 2.1, False, False, "Left flick exit"),
            ("Turn 11", 4, 160, 2.9, False, False, "Fast right uphill exit"),
            ("Turn 12", 6, 240, 3.4, False, False, "Blind crest left plunge"),
            ("Turn 13", 7, 275, 3.6, False, False, "Full throttle downhill sweep"),
            ("Turn 14", 7, 285, 3.5, False, False, "High speed kink"),
            ("Turn 15", 3, 120, 2.7, True, False, "Downhill left entry with barrier danger"),
            ("Turn 16", 3, 125, 2.6, True, False, "Left turn onto flat-out seaside sprint"),
            ("Turn 17", 7, 290, 3.2, False, False, "Flat-out sweep"),
            ("Turn 18", 8, 310, 3.1, False, False, "Full throttle left bend"),
            ("Turn 19", 8, 325, 2.8, False, False, "Flat-out right kink"),
            ("Turn 20", 8, 340, 2.5, False, True, "Final flat-out kink onto 2.2km main straight")
        ]
    },
    {
        "id": 9,
        "svg_file": "cota.svg",
        "circuit_name": "Circuit of the Americas (COTA)",
        "location": "Austin",
        "country": "United States",
        "country_code": "USA",
        "lat": 30.1328,
        "lng": -97.6411,
        "length_km": 5.513,
        "corners_count": 20,
        "drs_zones": 2,
        "lap_record": "1:36.169",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2019,
        "lap_record_team": "Ferrari SF90",
        "full_throttle_pct": 58,
        "downforce_level": "HIGH",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 56,
        "pit_loss_time_sec": 23.5,
        "first_grand_prix_year": 2012,
        "elevation_gain_m": 40.5,
        "description": "Modern American classic. Steep 41-meter uphill climb to blind apex Turn 1, followed by a relentless Becketts-inspired high-G sweeping sector.",
        "corner_names": [
            ("Big Red (T1)", 2, 85, 2.2, True, False, "Steep 41m uphill climb to blind hairpin apex"),
            ("Esses (T2)", 6, 255, 3.8, False, False, "Fast downhill right"),
            ("Esses (T3)", 6, 265, 4.3, False, False, "High-G left transition"),
            ("Esses (T4)", 6, 250, 4.4, False, False, "Right sweep matching Maggotts rhythm"),
            ("Esses (T5)", 6, 240, 4.2, False, False, "Left sweep"),
            ("Esses (T6)", 5, 215, 3.9, False, False, "Right curve"),
            ("Turn 7", 4, 165, 3.2, False, False, "Left uphill flick"),
            ("Turn 8", 4, 150, 2.9, False, False, "Tight left transition"),
            ("Turn 9", 4, 160, 3.1, False, False, "Blind crest right"),
            ("Turn 10", 5, 210, 3.4, False, False, "Downhill left leading to back straight"),
            ("Turn 11", 2, 75, 2.0, True, False, "Tight left hairpin before 1km back straight"),
            ("Turn 12", 2, 85, 2.4, True, False, "Heavy braking left at end of back straight"),
            ("Turn 13", 3, 115, 2.6, False, False, "Right transition"),
            ("Turn 14", 3, 125, 2.7, False, False, "Right sweeper"),
            ("Turn 15", 2, 90, 2.2, True, False, "Tight left around amphitheatre"),
            ("Carousel (T16)", 5, 210, 4.2, False, False, "Triple-apex right inspired by Istanbul Turn 8"),
            ("Carousel (T17)", 5, 220, 4.5, False, False, "Second apex continuous G load"),
            ("Carousel (T18)", 6, 235, 4.3, False, False, "Third apex high-speed launch"),
            ("Turn 19", 4, 175, 3.5, False, False, "Fast left over off-camber crest"),
            ("Turn 20", 3, 110, 2.4, True, True, "90-degree left onto pit straight")
        ]
    },
    {
        "id": 10,
        "svg_file": "spielberg.svg",
        "circuit_name": "Red Bull Ring (Spielberg)",
        "location": "Spielberg",
        "country": "Austria",
        "country_code": "AUT",
        "lat": 47.2197,
        "lng": 14.7647,
        "length_km": 4.318,
        "corners_count": 10,
        "drs_zones": 3,
        "lap_record": "1:05.619",
        "lap_record_driver": "Carlos Sainz",
        "lap_record_year": 2020,
        "lap_record_team": "McLaren MCL35",
        "full_throttle_pct": 68,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 36,
        "pit_loss_time_sec": 21.6,
        "first_grand_prix_year": 1970,
        "elevation_gain_m": 63.5,
        "description": "Short, punchy Styrian mountain circuit. High elevation changes, heavy braking zones, and three consecutive DRS zones creating non-stop action.",
        "corner_names": [
            ("Niki Lauda Kurve (T1)", 3, 135, 2.6, True, False, "Uphill right onto first DRS straight"),
            ("Remus (T3)", 2, 72, 2.1, True, False, "Steep uphill right hairpin - key overtaking spot"),
            ("Schlossgold (T4)", 3, 120, 2.8, True, False, "Downhill right entry with tricky track limits"),
            ("Rauch (T5)", 4, 175, 3.2, False, False, "Fast left into downhill infield"),
            ("Turn 6", 5, 205, 3.6, False, False, "Long sweeping downhill left"),
            ("Turn 7", 5, 215, 3.7, False, False, "Fast left kink"),
            ("Würth (T8)", 5, 220, 3.5, False, False, "Fast right transition"),
            ("Rindt (T9)", 6, 240, 4.1, False, False, "High speed downhill right"),
            ("Red Bull Mobile (T10)", 5, 210, 3.8, False, True, "Fast right launching onto main straight"),
            ("Main Straight (T2 Kink)", 8, 315, 2.2, False, False, "Slight uphill kink on DRS straight")
        ]
    },
    {
        "id": 11,
        "svg_file": "montreal.svg",
        "circuit_name": "Circuit Gilles Villeneuve",
        "location": "Montreal",
        "country": "Canada",
        "country_code": "CAN",
        "lat": 45.5000,
        "lng": -73.5228,
        "length_km": 4.361,
        "corners_count": 14,
        "drs_zones": 3,
        "lap_record": "1:13.078",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2019,
        "lap_record_team": "Mercedes W10",
        "full_throttle_pct": 60,
        "downforce_level": "LOW-MEDIUM",
        "tyre_stress_level": 2,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 52,
        "pit_loss_time_sec": 21.2,
        "first_grand_prix_year": 1978,
        "elevation_gain_m": 5.2,
        "description": "Stop-and-go island circuit on Île Notre-Dame. Punishing kerb riding, massive brake degradation, and the infamous Wall of Champions.",
        "corner_names": [
            ("Virage Senna (T1)", 3, 125, 2.4, True, False, "Left entry into Senna S chicane"),
            ("Virage Senna (T2)", 2, 75, 1.9, False, False, "Tight right hairpin exit"),
            ("Turn 3", 4, 150, 2.8, True, False, "Right entry chicane over kerbs"),
            ("Turn 4", 4, 160, 2.9, False, False, "Left exit clipping concrete wall"),
            ("Turn 5", 6, 245, 3.4, False, False, "Fast right sweep"),
            ("Turn 6", 3, 110, 2.5, True, False, "Left turn entry"),
            ("Turn 7", 4, 140, 2.7, False, False, "Right exit acceleration"),
            ("Turn 8", 4, 155, 2.9, True, False, "Right entry into fast chicane"),
            ("Turn 9", 4, 165, 3.0, False, False, "Left exit towards hairpin"),
            ("L'Epingle (T10)", 2, 65, 1.8, True, False, "Heavy deceleration 180-degree right hairpin"),
            ("Turn 11", 6, 250, 2.8, False, False, "Exit kink onto Droit du Casino straight"),
            ("Turn 12", 7, 290, 2.5, False, False, "Full throttle kink on back straight"),
            ("Wall of Champions (T13)", 3, 130, 3.1, True, False, "Right entry riding high kerbs"),
            ("Wall of Champions (T14)", 4, 155, 3.3, False, True, "Left exit brushing the infamous Wall of Champions")
        ]
    },
    {
        "id": 12,
        "svg_file": "zandvoort.svg",
        "circuit_name": "Circuit Zandvoort",
        "location": "Zandvoort",
        "country": "Netherlands",
        "country_code": "NED",
        "lat": 52.3888,
        "lng": 4.5409,
        "length_km": 4.259,
        "corners_count": 14,
        "drs_zones": 2,
        "lap_record": "1:11.097",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "lap_record_team": "Mercedes W12",
        "full_throttle_pct": 55,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 46,
        "pit_loss_time_sec": 22.0,
        "first_grand_prix_year": 1952,
        "elevation_gain_m": 15.0,
        "description": "Old-school seaside rollercoaster with extreme 18-degree banking at Hugenholtz and Arie Luyendyk curves, demanding high downforce.",
        "corner_names": [
            ("Tarzanbocht (T1)", 2, 95, 2.4, True, False, "Iconic horseshoe right hairpin"),
            ("Gerlachbocht (T2)", 4, 175, 3.1, False, False, "Fast right sweep"),
            ("Hugenholtzbocht (T3)", 3, 110, 3.2, False, False, "Extreme 19-degree progressive banking left"),
            ("Hunserug (T4)", 6, 255, 3.5, False, False, "Blind uphill crest right"),
            ("Rob Slotemakerbocht (T5)", 6, 260, 3.6, False, False, "Fast sweeping bend"),
            ("Turn 6", 5, 220, 3.8, False, False, "Right uphill entry"),
            ("Scheivlak (T7)", 6, 250, 4.4, False, False, "Epic blind downhill right - supreme commitment"),
            ("Mastersbocht (T8)", 5, 205, 3.7, False, False, "Right downhill plunge"),
            ("Turn 9", 4, 155, 2.9, True, False, "Right entry"),
            ("Turn 10", 3, 125, 2.5, True, False, "Left turn onto short straight"),
            ("Hans Ernst Bocht (T11)", 3, 115, 2.6, True, False, "Right chicane entry"),
            ("Hans Ernst Bocht (T12)", 3, 125, 2.7, False, False, "Left chicane exit"),
            ("Kumhobocht (T13)", 5, 215, 3.4, False, False, "Right turn leading into final banking"),
            ("Arie Luyendykbocht (T14)", 7, 275, 4.1, False, True, "18-degree banked right with early DRS activation")
        ]
    },
    {
        "id": 13,
        "svg_file": "bahrain.svg",
        "circuit_name": "Bahrain International Circuit",
        "location": "Sakhir",
        "country": "Bahrain",
        "country_code": "BHR",
        "lat": 26.0325,
        "lng": 50.5106,
        "length_km": 5.412,
        "corners_count": 15,
        "drs_zones": 3,
        "lap_record": "1:31.447",
        "lap_record_driver": "Pedro de la Rosa",
        "lap_record_year": 2005,
        "lap_record_team": "McLaren MP4-20",
        "full_throttle_pct": 64,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 5,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 58,
        "pit_loss_time_sec": 24.5,
        "first_grand_prix_year": 2004,
        "elevation_gain_m": 17.5,
        "description": "Desert floodlit oasis. Extreme rear tyre degradation, high thermal stress, and tough lockup-prone downhill braking at Turn 10.",
        "corner_names": [
            ("Michael Schumacher (T1)", 2, 75, 2.2, True, False, "Heavy braking right hairpin at end of main straight"),
            ("Turn 2", 3, 125, 2.5, False, False, "Left acceleration sweep"),
            ("Turn 3", 4, 175, 2.8, False, False, "Right flick onto DRS straight"),
            ("Turn 4", 3, 135, 2.7, True, False, "Downhill right entry with tricky off-camber exit"),
            ("Turn 5", 5, 220, 3.5, False, False, "Fast left entry into Esses"),
            ("Turn 6", 5, 210, 3.6, False, False, "Right sweep"),
            ("Turn 7", 5, 215, 3.4, False, False, "Left uphill flick"),
            ("Turn 8", 2, 75, 1.9, True, False, "Tight right hairpin"),
            ("Turn 9", 4, 165, 2.8, False, False, "Blind downhill crest left leading to T10"),
            ("Turn 10", 2, 70, 2.0, True, False, "Extreme downhill off-camber left - notorious for lockups"),
            ("Turn 11", 5, 215, 3.5, False, False, "Fast uphill left sweeper"),
            ("Turn 12", 6, 260, 3.8, False, False, "Flat out right sweep"),
            ("Turn 13", 4, 155, 3.0, True, False, "Right turn launching onto back straight"),
            ("Turn 14", 3, 120, 2.6, True, False, "Heavy braking right"),
            ("Turn 15", 5, 195, 3.0, False, True, "Right acceleration onto start/finish straight")
        ]
    },
    {
        "id": 14,
        "svg_file": "jeddah.svg",
        "circuit_name": "Jeddah Corniche Circuit",
        "location": "Jeddah",
        "country": "Saudi Arabia",
        "country_code": "SAU",
        "lat": 21.6319,
        "lng": 39.1044,
        "length_km": 6.174,
        "corners_count": 27,
        "drs_zones": 3,
        "lap_record": "1:30.734",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2021,
        "lap_record_team": "Mercedes W12",
        "full_throttle_pct": 79,
        "downforce_level": "LOW",
        "tyre_stress_level": 3,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 60,
        "pit_loss_time_sec": 22.5,
        "first_grand_prix_year": 2021,
        "elevation_gain_m": 4.5,
        "description": "The Fastest Street Circuit on Earth. 27 flowing high-speed bends nestled along the Red Sea coast with average speeds exceeding 250 km/h.",
        "corner_names": [
            ("Turn 1", 3, 115, 2.5, True, False, "Left entry chicane from 330 km/h"),
            ("Turn 2", 3, 125, 2.6, False, False, "Right chicane exit"),
            ("Turn 3", 5, 210, 3.4, False, False, "Fast left"),
            ("Turn 4", 6, 250, 4.0, False, False, "High speed sweeping right"),
            ("Turn 5", 6, 260, 4.2, False, False, "Left curve"),
            ("Turn 6", 6, 255, 4.1, False, False, "Right curve"),
            ("Turn 7", 6, 260, 4.2, False, False, "Left sweep"),
            ("Turn 8", 6, 265, 4.3, False, False, "Right sweep"),
            ("Turn 9", 6, 270, 4.2, False, False, "Left flick"),
            ("Turn 10", 6, 275, 4.0, False, False, "Right bend"),
            ("Turn 11", 6, 280, 3.8, False, False, "Left bend"),
            ("Turn 12", 7, 290, 3.6, False, False, "Right kink"),
            ("Turn 13", 4, 155, 3.8, True, False, "12-degree banked hairpin left"),
            ("Turn 14", 6, 260, 3.6, False, False, "Right exit"),
            ("Turn 15", 6, 265, 3.7, False, False, "Left curve"),
            ("Turn 16", 6, 270, 3.9, False, False, "Right curve"),
            ("Turn 17", 6, 275, 4.0, False, False, "Left curve"),
            ("Turn 18", 6, 280, 3.9, False, False, "Right curve"),
            ("Turn 19", 6, 285, 3.8, False, False, "Left curve"),
            ("Turn 20", 7, 295, 3.6, False, False, "Fast right sweep"),
            ("Turn 21", 7, 300, 3.5, False, False, "High speed left"),
            ("Turn 22", 6, 250, 4.5, True, False, "Blind high-G chicane left entry"),
            ("Turn 23", 6, 245, 4.4, False, False, "Right transition"),
            ("Turn 24", 7, 290, 3.6, False, False, "Left sweep"),
            ("Turn 25", 8, 310, 3.2, False, False, "Full throttle left bend"),
            ("Turn 26", 8, 320, 2.9, False, False, "Flat-out right kink"),
            ("Turn 27", 3, 110, 2.6, True, True, "Hairpin left onto pit straight")
        ]
    },
    {
        "id": 15,
        "svg_file": "melbourne.svg",
        "circuit_name": "Albert Park Circuit",
        "location": "Melbourne",
        "country": "Australia",
        "country_code": "AUS",
        "lat": -37.8497,
        "lng": 144.968,
        "length_km": 5.278,
        "corners_count": 14,
        "drs_zones": 4,
        "lap_record": "1:19.813",
        "lap_record_driver": "Charles Leclerc",
        "lap_record_year": 2024,
        "lap_record_team": "Ferrari SF-24",
        "full_throttle_pct": 68,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 50,
        "pit_loss_time_sec": 20.8,
        "first_grand_prix_year": 1996,
        "elevation_gain_m": 2.6,
        "description": "Scenic parkland circuit around Albert Park Lake. High evolution track surface, four rapid DRS zones, and high-speed T9-T10 sweepers.",
        "corner_names": [
            ("Turn 1", 4, 155, 3.0, True, False, "Right entry chicane at end of main straight"),
            ("Turn 2", 4, 165, 3.2, False, False, "Left exit acceleration"),
            ("Turn 3", 2, 90, 2.2, True, False, "Heavy braking right hairpin - prime overtaking"),
            ("Turn 4", 3, 125, 2.5, False, False, "Left exit onto lakeside sprint"),
            ("Turn 5", 6, 245, 3.6, False, False, "Fast right sweep"),
            ("Turn 6", 4, 155, 3.0, True, False, "Right turn entry"),
            ("Turn 7", 5, 210, 3.4, False, False, "Left acceleration sweep"),
            ("Turn 8", 6, 260, 3.6, False, False, "Fast right flick"),
            ("Turn 9", 7, 275, 4.6, False, False, "Epic flat-out high-G left sweeper"),
            ("Turn 10", 7, 280, 4.5, False, False, "High speed right transition"),
            ("Turn 11", 4, 160, 3.1, True, False, "Right-left chicane entry"),
            ("Turn 12", 4, 170, 3.2, False, False, "Chicane exit"),
            ("Turn 13", 3, 115, 2.4, True, False, "Slow right turn into stadium section"),
            ("Turn 14", 4, 145, 2.8, False, True, "Medium-speed left launching onto main straight")
        ]
    },
    {
        "id": 16,
        "svg_file": "shanghai.svg",
        "circuit_name": "Shanghai International Circuit",
        "location": "Shanghai",
        "country": "China",
        "country_code": "CHN",
        "lat": 31.3389,
        "lng": 121.22,
        "length_km": 5.451,
        "corners_count": 16,
        "drs_zones": 2,
        "lap_record": "1:32.238",
        "lap_record_driver": "Michael Schumacher",
        "lap_record_year": 2004,
        "lap_record_team": "Ferrari F2004",
        "full_throttle_pct": 53,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 52,
        "pit_loss_time_sec": 24.2,
        "first_grand_prix_year": 2004,
        "elevation_gain_m": 7.4,
        "description": "Shaped after the Chinese character 'Shang' (上). Famous for the endless 270-degree snail corner (Turns 1-4) and 1.2km back straight.",
        "corner_names": [
            ("Turn 1", 5, 225, 3.2, False, False, "High-speed right entry into decreasing radius snail"),
            ("Turn 2", 3, 115, 2.5, False, False, "Tightening right spiral"),
            ("Turn 3", 2, 80, 1.9, True, False, "Tight right bottom apex"),
            ("Turn 4", 3, 125, 2.6, False, False, "Left launch exit out of snail"),
            ("Turn 5", 6, 255, 3.2, False, False, "Full throttle right kink"),
            ("Turn 6", 2, 75, 2.0, True, False, "Heavy braking right hairpin"),
            ("Turn 7", 5, 215, 3.8, False, False, "High-speed left sweep"),
            ("Turn 8", 5, 220, 3.9, False, False, "High-G right sweep"),
            ("Turn 9", 3, 120, 2.6, True, False, "Left turn"),
            ("Turn 10", 4, 150, 2.8, False, False, "Left exit acceleration"),
            ("Turn 11", 3, 110, 2.4, True, False, "Left chicane entry"),
            ("Turn 12", 4, 145, 2.7, False, False, "Right exit"),
            ("Turn 13", 6, 240, 3.6, False, False, "Long banked right launching onto 1.2km back straight"),
            ("Turn 14", 2, 70, 2.1, True, False, "Extreme 340 km/h braking zone into tight right hairpin"),
            ("Turn 15", 3, 120, 2.4, False, False, "Left acceleration exit"),
            ("Turn 16", 5, 195, 3.2, False, True, "Fast left onto pit straight")
        ]
    },
    {
        "id": 17,
        "svg_file": "miami.svg",
        "circuit_name": "Miami International Autodrome",
        "location": "Miami",
        "country": "United States",
        "country_code": "USA",
        "lat": 25.9581,
        "lng": -80.2389,
        "length_km": 5.412,
        "corners_count": 19,
        "drs_zones": 3,
        "lap_record": "1:29.708",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "lap_record_team": "Red Bull RB19",
        "full_throttle_pct": 58,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 54,
        "pit_loss_time_sec": 22.8,
        "first_grand_prix_year": 2022,
        "elevation_gain_m": 9.0,
        "description": "Around Hard Rock Stadium. Blends fast sweeping curves with tight Mickey-Mouse chicanes and long high-speed DRS straights.",
        "corner_names": [
            ("Turn 1", 3, 115, 2.5, True, False, "Right-hander at end of main straight"),
            ("Turn 2", 4, 155, 2.8, False, False, "Left acceleration"),
            ("Turn 3", 5, 210, 3.2, False, False, "Right sweep"),
            ("Turn 4", 6, 255, 3.9, False, False, "High speed left sweeper"),
            ("Turn 5", 6, 260, 4.1, False, False, "Fast right transition"),
            ("Turn 6", 6, 250, 4.0, False, False, "Left sweep"),
            ("Turn 7", 5, 210, 3.5, False, False, "Right curve"),
            ("Turn 8", 4, 160, 2.9, True, False, "Left entry"),
            ("Turn 9", 5, 220, 3.2, False, False, "Fast left"),
            ("Turn 10", 6, 260, 3.4, False, False, "Right sweep"),
            ("Turn 11", 2, 75, 2.0, True, False, "Left hairpin before marina"),
            ("Turn 12", 3, 120, 2.4, False, False, "Right transition"),
            ("Turn 13", 4, 150, 2.8, False, False, "Left sweep"),
            ("Turn 14", 2, 60, 1.7, True, False, "Uphill slow chicane entry under turnpike"),
            ("Turn 15", 2, 70, 1.8, False, False, "Blind downhill chicane exit"),
            ("Turn 16", 4, 165, 3.0, False, False, "Left sweep launching onto 1.28km back straight"),
            ("Turn 17", 2, 75, 2.1, True, False, "Heavy braking left hairpin at end of back straight"),
            ("Turn 18", 4, 160, 2.8, False, False, "Left acceleration"),
            ("Turn 19", 5, 195, 3.2, False, True, "Fast left onto pit straight")
        ]
    },
    {
        "id": 18,
        "svg_file": "catalunya.svg",
        "circuit_name": "Circuit de Barcelona-Catalunya",
        "location": "Montmeló",
        "country": "Spain",
        "country_code": "ESP",
        "lat": 41.57,
        "lng": 2.2611,
        "length_km": 4.657,
        "corners_count": 14,
        "drs_zones": 2,
        "lap_record": "1:16.330",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "lap_record_team": "Red Bull RB19",
        "full_throttle_pct": 60,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 46,
        "pit_loss_time_sec": 22.0,
        "first_grand_prix_year": 1991,
        "elevation_gain_m": 29.5,
        "description": "Aerodynamic testing benchmark. Long right-hand Renault curve (Turn 3) and restored high-speed final sector testing total chassis balance.",
        "corner_names": [
            ("Elf (T1)", 3, 135, 2.8, True, False, "Right entry chicane at end of 1km main straight"),
            ("Elf (T2)", 3, 145, 2.9, False, False, "Left exit transition"),
            ("Curva Renault (T3)", 5, 225, 4.4, False, False, "Iconic long flat-out uphill right sweeper with huge lateral G"),
            ("Repsol (T4)", 3, 125, 2.6, True, False, "Right-hand hairpin over crest"),
            ("Seat (T5)", 2, 85, 2.1, True, False, "Downhill left hairpin"),
            ("Turn 6", 5, 215, 3.2, False, False, "Uphill left kink"),
            ("Campsa (T7)", 4, 160, 3.0, True, False, "Left turn entry"),
            ("Campsa (T8)", 5, 210, 3.5, False, False, "Uphill blind right"),
            ("Campsa (T9)", 6, 255, 4.2, False, False, "High speed blind right crest - massive commitment"),
            ("La Caixa (T10)", 2, 75, 2.2, True, False, "Heavy braking left hairpin"),
            ("Turn 11", 4, 155, 2.8, False, False, "Uphill right"),
            ("Banc Sabadell (T12)", 4, 165, 3.0, False, False, "Long right"),
            ("Turn 13", 6, 245, 4.2, False, False, "Restored high-speed right corner"),
            ("Turn 14", 7, 275, 4.5, False, True, "Epic flat-out right launching onto pit straight")
        ]
    },
    {
        "id": 19,
        "svg_file": "hungaroring.svg",
        "circuit_name": "Hungaroring",
        "location": "Mogyoród",
        "country": "Hungary",
        "country_code": "HUN",
        "lat": 47.5789,
        "lng": 19.2486,
        "length_km": 4.381,
        "corners_count": 14,
        "drs_zones": 2,
        "lap_record": "1:16.627",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "lap_record_team": "Mercedes W11",
        "full_throttle_pct": 52,
        "downforce_level": "MAXIMUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 50,
        "pit_loss_time_sec": 21.5,
        "first_grand_prix_year": 1986,
        "elevation_gain_m": 34.0,
        "description": "Monaco without the walls. Non-stop twisty valley circuit requiring maximum aerodynamic downforce, chassis nimbleness, and precise tyre management.",
        "corner_names": [
            ("Turn 1", 2, 95, 2.4, True, False, "Downhill right hairpin at end of pit straight"),
            ("Turn 2", 3, 125, 2.6, True, False, "Downhill off-camber left"),
            ("Turn 3", 5, 220, 3.4, False, False, "Fast uphill right onto short straight"),
            ("Mansell (T4)", 6, 245, 4.2, False, False, "Blind uphill crest left - supreme bravery"),
            ("Turn 5", 4, 155, 3.0, True, False, "Long sweeping uphill right"),
            ("Chicane (T6)", 2, 85, 2.1, True, False, "Slow chicane right entry over kerbs"),
            ("Chicane (T7)", 2, 95, 2.2, False, False, "Left chicane exit"),
            ("Turn 8", 4, 165, 3.1, False, False, "Left turn"),
            ("Turn 9", 4, 170, 3.2, False, False, "Right flick"),
            ("Turn 10", 5, 215, 3.6, False, False, "Fast left"),
            ("Turn 11", 5, 225, 3.8, False, False, "High speed right sweep"),
            ("Turn 12", 3, 120, 2.5, True, False, "90-degree right at top of hill"),
            ("Turn 13", 3, 115, 2.4, True, False, "Long left hairpin"),
            ("Turn 14", 4, 150, 2.9, False, True, "Double-apex right launching onto main straight")
        ]
    },
    {
        "id": 20,
        "svg_file": "mexico.svg",
        "circuit_name": "Autódromo Hermanos Rodríguez",
        "location": "Mexico City",
        "country": "Mexico",
        "country_code": "MEX",
        "lat": 19.4042,
        "lng": -99.0907,
        "length_km": 4.304,
        "corners_count": 17,
        "drs_zones": 3,
        "lap_record": "1:17.774",
        "lap_record_driver": "Valtteri Bottas",
        "lap_record_year": 2021,
        "lap_record_team": "Mercedes W12",
        "full_throttle_pct": 52,
        "downforce_level": "MAXIMUM",
        "tyre_stress_level": 2,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 22.8,
        "first_grand_prix_year": 1963,
        "elevation_gain_m": 2240.0,
        "description": "High altitude (2,240m above sea level) thin air creating low downforce with maximum aero wings, passing right through the Foro Sol baseball stadium.",
        "corner_names": [
            ("Moises Solana (T1)", 2, 95, 2.3, True, False, "Heavy braking right after 350 km/h straight"),
            ("Moises Solana (T2)", 3, 115, 2.5, False, False, "Left transition"),
            ("Moises Solana (T3)", 3, 125, 2.6, False, False, "Right exit onto DRS straight"),
            ("Turn 4", 2, 90, 2.2, True, False, "Heavy braking left hairpin"),
            ("Turn 5", 3, 120, 2.4, False, False, "Right transition"),
            ("Turn 6", 3, 130, 2.6, False, False, "Slow right chicane exit"),
            ("Esses (T7)", 5, 205, 3.4, False, False, "Fast left entry into flowing Esses"),
            ("Esses (T8)", 5, 215, 3.6, False, False, "Right flick"),
            ("Esses (T9)", 5, 220, 3.8, False, False, "Left flick"),
            ("Esses (T10)", 6, 235, 4.0, False, False, "Right curve"),
            ("Esses (T11)", 6, 240, 4.1, False, False, "Left launch"),
            ("Turn 12", 3, 120, 2.5, True, False, "Right turn leading to stadium entrance"),
            ("Foro Sol (T13)", 2, 65, 1.7, True, False, "Slow left entry into stadium baseball bowl"),
            ("Foro Sol (T14)", 2, 75, 1.8, False, False, "Right hairpin amidst 30,000 roaring fans"),
            ("Foro Sol (T15)", 2, 85, 2.0, False, False, "Left flick"),
            ("Turn 16", 3, 125, 2.4, False, False, "Right acceleration exit out of stadium"),
            ("Mansell Kurve (T17)", 6, 245, 3.8, False, True, "Fast right launching onto 1.3km pit straight")
        ]
    },
    {
        "id": 21,
        "svg_file": "las_vegas.svg",
        "circuit_name": "Las Vegas Strip Circuit",
        "location": "Las Vegas",
        "country": "United States",
        "country_code": "USA",
        "lat": 36.1147,
        "lng": -115.163,
        "length_km": 6.201,
        "corners_count": 17,
        "drs_zones": 2,
        "lap_record": "1:35.490",
        "lap_record_driver": "Oscar Piastri",
        "lap_record_year": 2023,
        "lap_record_team": "McLaren MCL60",
        "full_throttle_pct": 74,
        "downforce_level": "LOW",
        "tyre_stress_level": 3,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 44,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 2023,
        "elevation_gain_m": 4.0,
        "description": "Glamorous night spectacle racing down the famous Las Vegas Boulevard past Bellagio, Caesars Palace, and the Sphere at 350+ km/h.",
        "corner_names": [
            ("Turn 1", 2, 85, 2.2, True, False, "Tight left hairpin off the start"),
            ("Turn 2", 3, 125, 2.5, False, False, "Right transition"),
            ("Turn 3", 4, 160, 2.8, False, False, "Right acceleration sweep"),
            ("Turn 4", 5, 210, 3.2, False, False, "Fast left"),
            ("Turn 5", 3, 115, 2.4, True, False, "90-degree right into Sphere complex"),
            ("Sphere (T6)", 4, 155, 3.0, False, False, "Long sweeping left around the Sphere"),
            ("Sphere (T7)", 4, 165, 3.1, False, False, "Left continuous radius"),
            ("Sphere (T8)", 4, 160, 3.0, False, False, "Left exit"),
            ("Turn 9", 3, 120, 2.5, True, False, "Right chicane entry"),
            ("Turn 10", 3, 130, 2.6, False, False, "Left exit onto Koval Lane"),
            ("Turn 11", 5, 215, 3.0, False, False, "Left kink"),
            ("Turn 12", 3, 110, 2.4, True, False, "Slow 90-degree left onto the Strip"),
            ("The Strip (T13)", 8, 335, 2.2, False, False, "Full throttle kink down 1.9km Vegas Strip"),
            ("Turn 14", 2, 80, 2.3, True, False, "Extreme braking left chicane at end of Strip"),
            ("Turn 15", 3, 120, 2.5, False, False, "Right transition"),
            ("Turn 16", 4, 155, 2.8, False, False, "Left sweep"),
            ("Turn 17", 6, 240, 3.6, False, True, "Fast left launching onto main straight")
        ]
    },
    {
        "id": 22,
        "svg_file": "lusail.svg",
        "circuit_name": "Lusail International Circuit",
        "location": "Lusail",
        "country": "Qatar",
        "country_code": "QAT",
        "lat": 25.4897,
        "lng": 51.4542,
        "length_km": 5.419,
        "corners_count": 16,
        "drs_zones": 1,
        "lap_record": "1:24.319",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2023,
        "lap_record_team": "Red Bull RB19",
        "full_throttle_pct": 62,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 46,
        "pit_loss_time_sec": 24.0,
        "first_grand_prix_year": 2021,
        "elevation_gain_m": 8.5,
        "description": "High-speed aerodynamic flow under floodlights. High sustained lateral G-forces and aggressive kerbs punishing tyres across medium and high-speed bends.",
        "corner_names": [
            ("Turn 1", 3, 125, 2.6, True, False, "Right entry hairpin from 330 km/h main straight"),
            ("Turn 2", 4, 160, 2.9, False, False, "Left acceleration sweep"),
            ("Turn 3", 5, 215, 3.5, False, False, "Fast right sweep"),
            ("Turn 4", 4, 155, 3.0, True, False, "Right turn entry"),
            ("Turn 5", 4, 165, 3.1, False, False, "Left transition"),
            ("Turn 6", 3, 110, 2.3, True, False, "Tight left hairpin"),
            ("Turn 7", 4, 155, 2.9, False, False, "Right sweep"),
            ("Turn 8", 5, 210, 3.4, False, False, "Fast left"),
            ("Turn 9", 5, 220, 3.6, False, False, "Fast right"),
            ("Turn 10", 4, 165, 3.1, True, False, "Left turn"),
            ("Turn 11", 5, 215, 3.5, False, False, "Right sweep"),
            ("Triple Right (T12)", 6, 250, 4.4, False, False, "First apex of massive high-G triple right complex"),
            ("Triple Right (T13)", 6, 260, 4.7, False, False, "Second apex continuous 4.5+ G loading"),
            ("Triple Right (T14)", 6, 255, 4.5, False, False, "Third apex exit"),
            ("Turn 15", 4, 150, 3.0, True, False, "Right turn"),
            ("Turn 16", 4, 160, 3.2, False, True, "Medium-speed right onto 1km pit straight")
        ]
    },
    {
        "id": 23,
        "svg_file": "yas_marina.svg",
        "circuit_name": "Yas Marina Circuit",
        "location": "Abu Dhabi",
        "country": "United Arab Emirates",
        "country_code": "UAE",
        "lat": 24.4672,
        "lng": 54.6031,
        "length_km": 5.281,
        "corners_count": 16,
        "drs_zones": 2,
        "lap_record": "1:26.103",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2021,
        "lap_record_team": "Red Bull RB16B",
        "full_throttle_pct": 64,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 56,
        "pit_loss_time_sec": 22.2,
        "first_grand_prix_year": 2009,
        "elevation_gain_m": 10.7,
        "description": "Championship twilight finale. Features the fast Turn 5 hairpin, 1.2km drag down the back straight, and the sweeping Turn 9 banked horseshoe.",
        "corner_names": [
            ("Turn 1", 4, 165, 3.0, True, False, "Medium-speed left off the start straight"),
            ("Turn 2", 6, 255, 3.5, False, False, "Fast uphill right"),
            ("Turn 3", 6, 265, 3.8, False, False, "High speed crest left"),
            ("Turn 4", 5, 215, 3.2, False, False, "Right downhill plunge"),
            ("Turn 5", 2, 75, 2.1, True, False, "Modified hairpin left onto 1.2km back straight"),
            ("Turn 6", 3, 115, 2.5, True, False, "Left chicane entry at end of back straight"),
            ("Turn 7", 3, 125, 2.6, False, False, "Right chicane exit"),
            ("Turn 8", 6, 255, 3.2, False, False, "Kink on second DRS straight"),
            ("Marsa Banked (T9)", 4, 155, 3.6, True, False, "5-degree banked long sweeping left hairpin"),
            ("Turn 10", 5, 210, 3.2, False, False, "Right acceleration sweep"),
            ("Turn 11", 4, 160, 2.9, True, False, "Right turn entry"),
            ("Turn 12", 3, 125, 2.5, False, False, "Left turn towards hotel"),
            ("Turn 13", 3, 115, 2.4, True, False, "Right turn under the illuminated W Hotel bridge"),
            ("Turn 14", 3, 120, 2.5, False, False, "Left turn passing hotel marina"),
            ("Turn 15", 4, 165, 3.0, False, False, "Right turn around marina"),
            ("Turn 16", 5, 195, 3.4, False, True, "Fast right launching onto pit straight")
        ]
    }
]

def generate_circuit_data():
    svg_dir = r'C:\KERS\f1-frontend\public\circuits-svg'
    circuits_out = []
    
    for c_meta in CIRCUITS_META:
        fp = os.path.join(svg_dir, c_meta["svg_file"])
        if not os.path.exists(fp):
            print(f"ERROR: Missing {fp}")
            continue
            
        track_d, sf_center, x_pts, y_pts = extract_track_points_and_sf(fp)
        
        # Calculate corner apex positions along the path
        n_corners = len(c_meta["corner_names"])
        N_PTS = len(x_pts)
        
        # We find peaks in curvature
        dx = np.gradient(x_pts)
        dy = np.gradient(y_pts)
        ddx = np.gradient(dx)
        ddy = np.gradient(dy)
        denom = (dx**2 + dy**2)**1.5
        denom[denom < 1e-6] = 1e-6
        curvature = np.abs(dx * ddy - dy * ddx) / denom
        
        window = 25
        kernel = np.ones(window)/window
        curv_smooth = np.convolve(np.tile(curvature, 3), kernel, mode='same')[N_PTS:2*N_PTS]
        
        min_dist = max(20, N_PTS // (n_corners * 3))
        peaks, props = find_peaks(curv_smooth, distance=min_dist, prominence=0.001)
        
        # Select best matching peaks or evenly space if needed
        if len(peaks) > n_corners:
            # pick top n_corners by prominence while preserving lap order
            prominences = props['prominences']
            top_indices = np.argsort(prominences)[-n_corners:]
            chosen_peaks = np.sort(peaks[top_indices])
        elif len(peaks) == n_corners:
            chosen_peaks = peaks
        else:
            # supplement with linear spacing along path
            chosen_peaks = np.linspace(50, N_PTS - 50, n_corners, dtype=int)
            
        corners = []
        for i, c_info in enumerate(c_meta["corner_names"]):
            name, gear, min_spd, lat_g, is_brake, is_drs, notes = c_info
            peak_idx = chosen_peaks[i] if i < len(chosen_peaks) else int((i / n_corners) * N_PTS)
            cx = round(float(x_pts[peak_idx]), 1)
            cy = round(float(y_pts[peak_idx]), 1)
            
            corners.append({
                "corner_number": i + 1,
                "corner_name": name,
                "gear": gear,
                "min_speed_kmh": min_spd,
                "lateral_g": lat_g,
                "brake_zone": is_brake,
                "drs_zone": is_drs,
                "notes": notes,
                "x": cx,
                "y": cy
            })
            
        circuit_dict = {
            "id": c_meta["id"],
            "circuit_name": c_meta["circuit_name"],
            "location": c_meta["location"],
            "country": c_meta["country"],
            "country_code": c_meta["country_code"],
            "lat": c_meta["lat"],
            "lng": c_meta["lng"],
            "length_km": c_meta["length_km"],
            "corners_count": c_meta["corners_count"],
            "drs_zones": c_meta["drs_zones"],
            "lap_record": c_meta["lap_record"],
            "lap_record_driver": c_meta["lap_record_driver"],
            "lap_record_year": c_meta["lap_record_year"],
            "lap_record_team": c_meta["lap_record_team"],
            "full_throttle_pct": c_meta["full_throttle_pct"],
            "downforce_level": c_meta["downforce_level"],
            "tyre_stress_level": c_meta["tyre_stress_level"],
            "brake_wear_index": c_meta["brake_wear_index"],
            "gear_shifts_per_lap": c_meta["gear_shifts_per_lap"],
            "pit_loss_time_sec": c_meta["pit_loss_time_sec"],
            "first_grand_prix_year": c_meta["first_grand_prix_year"],
            "elevation_gain_m": c_meta["elevation_gain_m"],
            "view_box": "0 0 500 500",
            "start_finish": {
                "x": round(sf_center[0], 1),
                "y": round(sf_center[1], 1),
                "label_x": 20,
                "label_y": 4
            },
            "description": c_meta["description"],
            "svg_path": track_d,
            "optimal_line_svg": track_d,
            "corners": corners
        }
        circuits_out.append(circuit_dict)
        print(f"Processed ID {c_meta['id']}: {c_meta['circuit_name']} ({len(corners)} corners)")
        
    return circuits_out

if __name__ == '__main__':
    data = generate_circuit_data()
    with open(r'C:\KERS\f1-backend\scripts\circuits_data.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)
    print(f"Saved {len(data)} circuits to circuits_data.json")
