import urllib.request
import json
import os
import re
import xml.etree.ElementTree as ET
import numpy as np

# Map of circuits after Yas Marina (ID 24 to 39)
CIRCUITS_CONFIG = [
    {
        "id": 24,
        "circuit_name": "Sepang International Circuit",
        "location": "Kuala Lumpur",
        "country": "Malaysia",
        "country_code": "MAL",
        "lat": 2.7606,
        "lng": 101.7381,
        "length_km": 5.543,
        "corners_count": 15,
        "drs_zones": 2,
        "lap_record": "1:34.080",
        "lap_record_driver": "Sebastian Vettel",
        "lap_record_year": 2017,
        "lap_record_team": "Ferrari SF70H",
        "full_throttle_pct": 65,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 52,
        "pit_loss_time_sec": 22.4,
        "first_grand_prix_year": 1999,
        "elevation_gain_m": 18.0,
        "repo_path": "circuits/detailed/white-outline/sepang-1.svg",
        "fallback_path": "circuits/minimal/white-outline/sepang-1.svg",
        "description": "Hermann Tilke's masterpiece. Extreme high-temperature tropical humidity, two massive 900m parallel straights separated by a hairpin, and high-speed swooping turns 5 and 6."
    },
    {
        "id": 25,
        "circuit_name": "Sochi Autodrom",
        "location": "Sochi",
        "country": "Russia",
        "country_code": "RUS",
        "lat": 43.4056,
        "lng": 39.9578,
        "length_km": 5.848,
        "corners_count": 18,
        "drs_zones": 2,
        "lap_record": "1:35.761",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2019,
        "lap_record_team": "Mercedes W10",
        "full_throttle_pct": 56,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 64,
        "pit_loss_time_sec": 25.0,
        "first_grand_prix_year": 2014,
        "elevation_gain_m": 4.5,
        "repo_path": "circuits/minimal/white-outline/sochi-1.svg",
        "description": "Olympic Park street track. Dominated by the monumental constant-radius 180-degree left-hand Turn 3 around the Medal Plaza."
    },
    {
        "id": 26,
        "circuit_name": "Hockenheimring",
        "location": "Hockenheim",
        "country": "Germany",
        "country_code": "GER",
        "lat": 49.3278,
        "lng": 8.5658,
        "length_km": 4.574,
        "corners_count": 17,
        "drs_zones": 2,
        "lap_record": "1:13.780",
        "lap_record_driver": "Kimi Räikkönen",
        "lap_record_year": 2004,
        "lap_record_team": "McLaren MP4-19B",
        "full_throttle_pct": 64,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 50,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 1970,
        "elevation_gain_m": 4.0,
        "repo_path": "circuits/minimal/white-outline/hockenheimring-4.svg",
        "description": "Historic German Grand Prix venue. The flat-out Parabolika curve leading to the tight hairpin overtake zone, followed by the roaring Motodrom stadium."
    },
    {
        "id": 27,
        "circuit_name": "Autodromo Enzo e Dino Ferrari (Imola)",
        "location": "Imola",
        "country": "Italy",
        "country_code": "ITA",
        "lat": 44.3439,
        "lng": 11.7167,
        "length_km": 4.909,
        "corners_count": 19,
        "drs_zones": 1,
        "lap_record": "1:15.484",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "lap_record_team": "Mercedes W11",
        "full_throttle_pct": 71,
        "downforce_level": "HIGH",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 58,
        "pit_loss_time_sec": 24.8,
        "first_grand_prix_year": 1980,
        "elevation_gain_m": 35.0,
        "repo_path": "circuits/minimal/white-outline/imola-3.svg",
        "description": "Historic anti-clockwise sanctuary in Emilia-Romagna. Featuring Tamburello chicane, the steep downhill Piratella plunge, and the challenging Acque Minerali kerbs."
    },
    {
        "id": 28,
        "circuit_name": "Istanbul Park",
        "location": "Istanbul",
        "country": "Turkey",
        "country_code": "TUR",
        "lat": 40.9517,
        "lng": 29.405,
        "length_km": 5.338,
        "corners_count": 14,
        "drs_zones": 2,
        "lap_record": "1:24.770",
        "lap_record_driver": "Juan Pablo Montoya",
        "lap_record_year": 2005,
        "lap_record_team": "McLaren MP4-20",
        "full_throttle_pct": 63,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 46,
        "pit_loss_time_sec": 22.0,
        "first_grand_prix_year": 2005,
        "elevation_gain_m": 46.0,
        "repo_path": "circuits/minimal/white-outline/istanbul-1.svg",
        "description": "The legendary anti-clockwise rollercoaster. Famous for Turn 8 — a quad-apex high-speed left-hander subjecting drivers to over 5G lateral loading for 7 continuous seconds."
    },
    {
        "id": 29,
        "circuit_name": "Nürburgring (GP-Strecke)",
        "location": "Nürburg",
        "country": "Germany",
        "country_code": "GER",
        "lat": 50.3356,
        "lng": 6.9475,
        "length_km": 5.148,
        "corners_count": 15,
        "drs_zones": 2,
        "lap_record": "1:28.139",
        "lap_record_driver": "Max Verstappen",
        "lap_record_year": 2020,
        "lap_record_team": "Red Bull RB16",
        "full_throttle_pct": 61,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 56,
        "pit_loss_time_sec": 23.5,
        "first_grand_prix_year": 1951,
        "elevation_gain_m": 56.0,
        "repo_path": "circuits/minimal/white-outline/nurburgring-4.svg",
        "description": "In the shadow of the Eifel mountains. The tricky Castrol S downhill entry, Mercedes-Arena amphitheatre, and the high-G Michael Schumacher S chicane."
    },
    {
        "id": 30,
        "circuit_name": "Circuit Paul Ricard",
        "location": "Le Castellet",
        "country": "France",
        "country_code": "FRA",
        "lat": 43.2506,
        "lng": 5.7917,
        "length_km": 5.842,
        "corners_count": 15,
        "drs_zones": 2,
        "lap_record": "1:32.740",
        "lap_record_driver": "Sebastian Vettel",
        "lap_record_year": 2019,
        "lap_record_team": "Ferrari SF90",
        "full_throttle_pct": 67,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 4,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 24.5,
        "first_grand_prix_year": 1971,
        "elevation_gain_m": 30.0,
        "repo_path": "circuits/minimal/white-outline/paul-ricard-1.svg",
        "description": "High-speed plateau on the Côte d'Azur. The 1.8km Mistral straight, punctuated by the chicane, leading into the heart-stopping flat-out Signes curve at 330 km/h."
    },
    {
        "id": 31,
        "circuit_name": "Circuit de Nevers Magny-Cours",
        "location": "Magny-Cours",
        "country": "France",
        "country_code": "FRA",
        "lat": 46.8642,
        "lng": 3.1636,
        "length_km": 4.411,
        "corners_count": 17,
        "drs_zones": 1,
        "lap_record": "1:15.377",
        "lap_record_driver": "Michael Schumacher",
        "lap_record_year": 2004,
        "lap_record_team": "Ferrari F2004",
        "full_throttle_pct": 66,
        "downforce_level": "HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 52,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 1991,
        "elevation_gain_m": 12.0,
        "repo_path": "circuits/minimal/white-outline/magny-cours-3.svg",
        "description": "Smooth technical French Grand Prix home. Famous for replicating corner layouts from around the world including the Adelaide hairpin, Estoril curve, and Nürburgring chicane."
    },
    {
        "id": 32,
        "circuit_name": "Indianapolis Motor Speedway (Road Course)",
        "location": "Speedway, Indiana",
        "country": "USA",
        "country_code": "USA",
        "lat": 39.795,
        "lng": -86.2344,
        "length_km": 4.192,
        "corners_count": 13,
        "drs_zones": 1,
        "lap_record": "1:10.399",
        "lap_record_driver": "Rubens Barrichello",
        "lap_record_year": 2004,
        "lap_record_team": "Ferrari F2004",
        "full_throttle_pct": 69,
        "downforce_level": "LOW-MEDIUM",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 44,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 2000,
        "elevation_gain_m": 0.0,
        "repo_path": "circuits/minimal/white-outline/indianapolis-1.svg",
        "description": "The Brickyard F1 road course. Tight infield sequence feeding directly onto the high-speed 9-degree banked Turn 13 oval bend across the legendary Yard of Bricks."
    },
    {
        "id": 33,
        "circuit_name": "Autódromo Internacional do Algarve (Portimão)",
        "location": "Portimão",
        "country": "Portugal",
        "country_code": "POR",
        "lat": 37.2272,
        "lng": -8.6267,
        "length_km": 4.653,
        "corners_count": 15,
        "drs_zones": 2,
        "lap_record": "1:18.750",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "lap_record_team": "Mercedes W11",
        "full_throttle_pct": 64,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 54,
        "pit_loss_time_sec": 22.0,
        "first_grand_prix_year": 2020,
        "elevation_gain_m": 38.0,
        "repo_path": "circuits/minimal/white-outline/portimao-1.svg",
        "description": "The Portuguese rollercoaster. Constant blind crests, severe gradient drops, and the spectacular downhill plunge into Turn 1."
    },
    {
        "id": 34,
        "circuit_name": "Buddh International Circuit",
        "location": "Greater Noida",
        "country": "India",
        "country_code": "IND",
        "lat": 28.3486,
        "lng": 77.5331,
        "length_km": 5.125,
        "corners_count": 16,
        "drs_zones": 2,
        "lap_record": "1:27.249",
        "lap_record_driver": "Sebastian Vettel",
        "lap_record_year": 2011,
        "lap_record_team": "Red Bull RB7",
        "full_throttle_pct": 64,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 54,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 2011,
        "elevation_gain_m": 14.0,
        "repo_path": "circuits/minimal/white-outline/buddh-1.svg",
        "description": "Indian Grand Prix home. Steep blind uphill braking into Turn 3 hairpin, a 1.06km straight reaching 335 km/h, and the sweeping double-apex Parabolica turns 10-11."
    },
    {
        "id": 35,
        "circuit_name": "Korea International Circuit",
        "location": "Yeongam",
        "country": "South Korea",
        "country_code": "KOR",
        "lat": 34.7333,
        "lng": 126.417,
        "length_km": 5.615,
        "corners_count": 18,
        "drs_zones": 2,
        "lap_record": "1:39.605",
        "lap_record_driver": "Sebastian Vettel",
        "lap_record_year": 2011,
        "lap_record_team": "Red Bull RB7",
        "full_throttle_pct": 61,
        "downforce_level": "MEDIUM-HIGH",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 58,
        "pit_loss_time_sec": 23.0,
        "first_grand_prix_year": 2010,
        "elevation_gain_m": 5.0,
        "repo_path": "circuits/minimal/white-outline/yeongam-1.svg",
        "description": "Unique hybrid venue. Sector 1 features a massive 1.2km full-throttle straight, transitioning into a tight marina street course with walls in Sectors 2 and 3."
    },
    {
        "id": 36,
        "circuit_name": "Valencia Street Circuit",
        "location": "Valencia",
        "country": "Spain",
        "country_code": "ESP",
        "lat": 39.4589,
        "lng": -0.3317,
        "length_km": 5.419,
        "corners_count": 25,
        "drs_zones": 2,
        "lap_record": "1:38.683",
        "lap_record_driver": "Timo Glock",
        "lap_record_year": 2009,
        "lap_record_team": "Toyota TF109",
        "full_throttle_pct": 61,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "VERY HEAVY",
        "gear_shifts_per_lap": 66,
        "pit_loss_time_sec": 21.5,
        "first_grand_prix_year": 2008,
        "elevation_gain_m": 2.0,
        "repo_path": "circuits/minimal/white-outline/valencia-1.svg",
        "description": "Spectacular marina harbour street track. Crosses a 140m operational swing bridge and features high-speed curved walls through 25 challenging turns."
    },
    {
        "id": 37,
        "circuit_name": "Autodromo Internazionale del Mugello",
        "location": "Scarperia e San Piero",
        "country": "Italy",
        "country_code": "ITA",
        "lat": 43.9975,
        "lng": 11.3714,
        "length_km": 5.245,
        "corners_count": 15,
        "drs_zones": 1,
        "lap_record": "1:18.833",
        "lap_record_driver": "Lewis Hamilton",
        "lap_record_year": 2020,
        "lap_record_team": "Mercedes W11",
        "full_throttle_pct": 69,
        "downforce_level": "HIGH",
        "tyre_stress_level": 5,
        "brake_wear_index": "MEDIUM",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 23.0,
        "first_grand_prix_year": 2020,
        "elevation_gain_m": 41.0,
        "repo_path": "circuits/minimal/white-outline/mugello-1.svg",
        "description": "Tuscan high-downforce temple. Relentless medium and high-speed flow, blind crests, and the breathtaking flat-out Arrabbiata 1 and 2 taken at 270 km/h."
    },
    {
        "id": 38,
        "circuit_name": "Fuji Speedway",
        "location": "Oyama",
        "country": "Japan",
        "country_code": "JPN",
        "lat": 35.3717,
        "lng": 138.927,
        "length_km": 4.563,
        "corners_count": 16,
        "drs_zones": 1,
        "lap_record": "1:18.426",
        "lap_record_driver": "Felipe Massa",
        "lap_record_year": 2008,
        "lap_record_team": "Ferrari F2008",
        "full_throttle_pct": 62,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 3,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 48,
        "pit_loss_time_sec": 21.0,
        "first_grand_prix_year": 1976,
        "elevation_gain_m": 40.0,
        "repo_path": "circuits/minimal/white-outline/fuji-2.svg",
        "description": "At the foot of Mount Fuji. One of motorsport's longest straights (1.475km) followed by extreme braking into the Turn 1 hairpin and the technical rising final sector."
    },
    {
        "id": 39,
        "circuit_name": "Circuito de Madring (Madrid)",
        "location": "Madrid",
        "country": "Spain",
        "country_code": "ESP",
        "lat": 40.4639,
        "lng": -3.6167,
        "length_km": 5.474,
        "corners_count": 20,
        "drs_zones": 3,
        "lap_record": "1:32.450",
        "lap_record_driver": "Carlos Sainz",
        "lap_record_year": 2026,
        "lap_record_team": "Williams FW48",
        "full_throttle_pct": 67,
        "downforce_level": "MEDIUM",
        "tyre_stress_level": 4,
        "brake_wear_index": "HEAVY",
        "gear_shifts_per_lap": 60,
        "pit_loss_time_sec": 22.0,
        "first_grand_prix_year": 2026,
        "elevation_gain_m": 16.0,
        "repo_path": "circuits/detailed/white-outline/madring-1.svg",
        "description": "The future of Spanish Formula 1. Hybrid street and permanent road circuit around the IFEMA exhibition centre with steep banked curves and high-speed tunnel transitions."
    }
]

print("Defined", len(CIRCUITS_CONFIG), "circuits after Yas Marina.")
