"""init

Revision ID: 92e4292d0734
Revises: 
Create Date: 2026-09-12 04:52:14.506154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92e4292d0734'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
